ARM-software/devlib

devlib/module/cpufreq.py, devlib/module/hotplug.py, devlib/target.py, devlib/utils/serial_port.py, devlib/utils/ssh.py
These are some fixes to make more robust the initialization of some modules.
=> Fixup some modules initialization

devlib/module/cgroups.py, devlib/utils/ssh.py
Here is a couple of fixups for the SSH connection problems, due to command being echoed, and a patch which refactors the CGroups module.
This last patch is not incremental, since it changes drastically the interface.
It's commit message should describe quite clearly how to use the new interface.
Validation has been done using an ipython notebook which is part of the (soon to be released) scheduler testing suite.
=> Fixes and additions for master

devlib/bin/scripts/shutils.in, devlib/module/cgroups.py
Some small fixes for the CGroup module.
=> Cgroup fixups

devlib/utils/android.py
Added automatic detection of new line separators
=> AdbConnection: added automatic detection of new line separators

doc/overview.rst
Fixes typos reported in issue #27
=> Fix typos in overview documentation

devlib/target.py
Most invocations of target.execute() pass as_root=self.is_rooted .
However, is_rooted is not what you want to do here.  as_root tells the
connection to wrap the command around sudo/su to execute the command as
root.  is_rooted returns True if the device can run commands as
root (for example, if we are connected as root).  If you are already
connected as root, there is no need to wrap the command around sudo, you
are already root.  In that case, as_root should always be false.
Define a new property for the target called needs_su that returns true
if the target needs to run a command to get superuser privileges.
=> devlib: don't use sudo/su if you are root

devlib/utils/ssh.py
These patches are intended to support the following use case:
1. The target device is started
2. devlib establishes a telnet connection to the device's root console
3. devlib waits for a prompt string, specified by the client
4. The target device does not prompt for a password: connection is now established
An example of this flow is connecting to the UART of an ARM FVP Fast Model.
=> TelnetConnection: support for systems which do not prompt for a password

devlib/module/cgroups.py
Here are some small cosmetics update for the recently merged freezer support.
=> Cgroups cosmetics

devlib/target.py
We expect ls to output single column listings. Previous to Linaro Android
16.09 release, this was the default. From the 16.09 release onwards, the
default is multi-column. Unfortunately, pre-16.09 ls does not support the
'-1' option to guarantee single column output.
Test for ls supporting '-1' and use it if possible.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
=> AndroidTarget: Handle ls format change in Android 7.0

devlib/trace/ftrace.py
Configuration sysfs files required by ftrace are usually accessible only by
the root user. In systems where ADB does not run as root by default, the
initialisation of the ftrace module fails.
This patch ensure that all ftrace commands are executed with root privileges.
=> ftrace: ensure ftrace commands are executed as root

devlib/module/cpufreq.py
I put this in while working on something for Lisa; I guess it belongs in here, if you disagree it can go in Lisa directly instead :)
=> cpufreq: Add function to get CPUs in frequency domain

devlib/utils/android.py
Similarly to other uses of ls, the change to multi-column default output
format has confused this API. Add in a similar routine to other objects
which use ls, so that we can try to figure out if we have a multi-column
default and control the output if so, or just use the plain command if
that doesn't work and hope it is still single column output.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
=> Fix adb pull with wildcard on Android v7+

devlib/host.py
Target::get_connection requires this.
=> LocalConnection: Add ignored 'timeout' __init__ param

devlib/utils/android.py
On older combinations of ADB/Android versions, the adb host command always
exits with 0 if it was able to run the command on the target, even if the
command failed (https://code.google.com/p/android/issues/detail?id=3254).
When we need the target's exit code (check_exit_code=True), we currently work
around this behaviour by echoing the target's exit code after the command and
parsing it out of the output.
The ADB behaviour is now "fixed" on newer versions with newer Androids (It's not
clear which versions these are and it appears that different builds of ADB with
the same version number differ in this respect). For those version combinations
adb_shell will currently raise a CalledProcessError when check_exit_code=False
and the target command fails.
So lets now use the "echo $?" trick …
=> android: Handle variation in ADB behaviour

devlib/host.py, doc/connection.rst
- Add glob support for `pull`.
This feature is supported implicitly by SshConnection and explicitly by
AdbConnection. Also add documentation for this feature.
- Add useful info in exception message when commands fail
=> Enhancements for LocalConnection

devlib/target.py, devlib/utils/android.py
Adding few APIs which could be useful to have in devlib
=> Android support updates

devlib/instrument/energy_probe.py
Looks like this is commit-leakage.
=> energy_probe: Remove unused pandas try-import

devlib/utils/ssh.py
This avoids a network round trip and speeds up SSH targets.
=> ssh: Combine exit code and main command

devlib/target.py, devlib/utils/ssh.py
The branch contains two commits: the first commit corrects a mistake in the gem5 pull method and the second commit adds a get_directory method to target.
=> Pull directory

devlib/utils/ssh.py
When providing a source file with wildcards (e.g. *ramp*.log)
to be pulled from the target, this might involve transferring
multiple files.
Add support for the transfer of multiple files in the pull method.
=> gem5: modify pull method to support transfer of multiple files

devlib/utils/android.py
If we execute a command such as:
'am start -a android.intent.action.VIEW -d nothing'
on Hikey960 with AOSP master, we do get an error message:
'Error: Activity not started, unable to resolve Intent ...'
but the error code is set to 0. Furthermore, that error message
is outputted to STDERR and not STDOUT.
The current error checking in adb_shell() is done by either
reading the error code or finding an error string in the
standard output. This commit adds a check of the error output,
and also changes the regular expression that is used to find
an error string as it wasn't generic enough.
=> utils/android: Fix error detection in adb_shell()

devlib/utils/ssh.py
On some platforms it might be better to use `su -c` instead of `sudo -- sh -c`
This patch doesn't change the current behaviour of devlib, just gives the user the option to change it.
=> Let the user customize the way to execute superuser commands

devlib/__init__.py, devlib/instrument/gem5power.py, devlib/module/gem5stats.py
This adds an instrument to enable power monitoring in Gem5 by parsing simulation statistics.
=> instrument: Add power monitoring support on Gem5 platforms

devlib/module/gem5stats.py
=> gem5stats: fix missing import for TargetError

devlib/utils/ssh.py
This is another case where we could do with a `ConnectionError` class but it's not a big deal I guess.
=> Improve SshConnection.push errors

devlib/utils/types.py
numeric() conversion function is expanded to handle percentage values in
the form "10.123%". The result is the numeric part converted to a float
and divided by 100, e.g. 0.10123.
=> utils/types: numeric expeanded to handle percentages

devlib/utils/android.py
I've been using the LogcatMonitor to run some Android benchmarks and found a few issues that didn't pop up when I ran simpler tests for #166. Here are the changes:
- `host.kill_children()` is used to properly kill the logcat process when it is IO blocked (uses #167).
- The logcat regexp argument is now within double quotes, as having parenthesis within the regexp could break the command.
- `LogcatMonitor.search()` has been renamed to `wait_for()` to make the behaviour of the method more explicit. A non-blocking version of this method has been added and is named `search()`. I don't like sudden API changes but I think this one is needed.
=> utils/android: LogcatMonitor fixes and improvements

devlib/target.py, doc/target.rst
This is for implementing the `requires_network` parameter in WA3..
=> target: Add is_network_connected method

devlib/utils/android.py
Currently if you never call wait_for, the underlying pexpect will not
read bytes from the logcat command's output into the log file. So
when we get into get_log, we need to force it to read all the
already-available bytes.
=> LogcatMonitor: Fix using get_log without wait_for

devlib/utils/android.py
Elsewhere in devlib, we strip '\r' characters and then handle it as if
it was just normal unix style '\n'.
However in adb_shell, we have a newline_separator option which defaults
to windows style '\r\n'.
This commit removes the newline_separator() function in the
AdbConnection class, removes the use of this function in execute()
function, and removes the parameter from adb_shell() function.
Instead, in the adb_shell() function, the same action as elsewhere in
devlib is performed: replace('\r\n', '\n').replace('\r', '\n')
=> Remove newline_separator from utils/android.py

devlib/utils/ssh.py
Minor gem5 fixes to address various issues when interacting.
=> Gem5 fixes

devlib/module/cpufreq.py
On intel_pstate machines, we can't get a list of available CPU
frequencies. In that case, return empty list as per the docastring.
=> cpufreq: Fix list_frequencies when not available

devlib/utils/misc.py, devlib/utils/ssh.py
Allow usage of push and pull via ssh with paths containing spaces.
=> SSH pull/push fix

devlib/target.py, doc/target.rst
Duplicate of previously closed PR #212 from @bjackman
=> Linux target push pull root

devlib/__init__.py, devlib/instrument/arm_energy_probe.py, devlib/utils/parse_aep.py
Add new energy instrument that is based on arm-probe tool to manage AEP
Main advantages of this tool are:
- uses a config file for describing channels and shunt resistors value
- manages power topology description in the config file. This topology
is then used when computing power figures
- can create virtual power channel and aggregate channels
- support multiple AEP
- support auto-zero of AEP's channel
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
=> Add a new Arm Energy Probe instrument

devlib/utils/ssh.py
Previously, when the gem5 simulation crashed, one would get errors
relating to pexpect reaching EOF, rather than an informative message
stating the gem5 itself had crashed. With this change, we catch some
of the common cases where this can happen, and inform the user if gem5
itself has crashed. In the event that the gem5 simulation itself has
not reported an error, we instead re-throw the original pexpect error.
=> gem5Connection: Catch EOF errors & make more user friendly

devlib/module/cgroups.py
Closes #241 
The tasks() function allows to get the tasks that are in a cgroup.
Filters for the tasks TID, name and cmdline have been added to the
parameters of the function such that it is possible to select the tasks
that match these patterns.
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
=> cgroups.py: Add filters for the tasks() function

devlib/target.py
Add a method to get info (apk path) for an installed package.
=> AndroidTarget: add get_pacakge_info

devlib/target.py
Add a method to dump XML UI hierarchy from uiautomator.
=> AndroidTarget: add capture_ui_hierarchy

devlib/platform/gem5.py, devlib/target.py
Add an option to format an ISO8601 timestamp into the screenshot file
name.
=> target: timestamp for capture_screen

devlib/utils/misc.py
Sub process.Popen (used internally by check_output) is not thread-safe
and may cause a thread to lock up if called simultaneously from multiple
threads. See
https://bugs.python.org/issue12739
This is fixed in Python 3.2, but since we're currently still on 2.7,
work around the issue by protecting the call with a lock.
=> utis/misc: make check_output thread-safe

devlib/instrument/__init__.py
Issue #276 illustrates the risk of having too many nested levels and
execution paths which also impact the readability of the code. We
modify the implementation to solve the bug on top of which we:
- Reduce the maximum order of nested levels from 4 to 3;
- Express more clearly the potential paths of execution
(less nested conditions);
- Replace unnecessary `for`-loops by list comprehensions,
removing the need for an initialisation of `active_channels`
and making clearer what each path of execution ends up with;
- Removed unnecessary `list` copies of `self.channels.values()`;
- Used the fact that the message of a `KeyError` is the unknown
key.
Some comments have also been added pointing out places in the code
where the logger could have been called: these are proposition to
be accepted …
=> Instrument.reset: fix when called with string kind & improve readability

devlib/utils/android.py
Add the more recent android versions to the version map.
=> utils/android: add recent Android versions

devlib/utils/ssh.py
Issues have been addressed, and the code has been tested from both WA and from a customised python script directly utilising devlib.
=> Add gem5 checkpoint support

devlib/target.py, devlib/utils/android.py
A collection of bits and bobs we have laying in LISA but that really belongs here.
=> Few additions to AndroidTarget

devlib/trace/systrace.py
Yet another LISA feature that truly belongs here.
=> trace: Add a Systrace TraceCollector

devlib/bin/scripts/shutils.in, devlib/target.py, doc/target.rst
Add a unique identifier for the target system.
=> Target.system_id

devlib/module/hotplug.py
This is similar to the list_{online/offline}_cpus helpers from Target
=> module/hotplug: Add list_hotpluggable_cpus helper

devlib/module/cpufreq.py
We may sometime want to temporarily use another governor, and then
restore whatever governor was used previously - for instance, RT-app
calibration ([1]) needs to use the performance governor, but we don't
want this to interfere with e.g. our current experiment.
[1]: https://github.com/ARM-software/lisa/blob/master/libs/wlgen/wlgen/rta.py#L118
=> module/cpufreq: Add a contextmanager for temporary governor changes

devlib/target.py
proposed fix for https://github.com/ARM-software/devlib/issues/317
=> target.py: cope with non-root users and with non-standard home directories

devlib/module/__init__.py, doc/modules.rst
Update documentation to include the 'setup' stage for module
initialization.
=> modules: Update docs with 'setup' stage for module initialization

devlib/target.py
Add a property to get the target's virtual memory page size in kB.
=> target: add page_size_kb property

devlib/module/cpufreq.py
Frequencies are not considered as governor tunables by
list_governor_tunables(), so add a special case to restore userspace
frequency when using use_governor().
While at it, reword the internal "governor" variable to not clash
with the parameter of the same name.
I was not sure if that should be handled in the tunables themselves (i.e. special-case `userspace` in `list_governor_tunables` & co) or if it was fine to special case them in the context manager. I went with this implementation to get the discussion going.
=> module/cpufreq: Add userspace special case for use_governor()

devlib/utils/ssh.py
=> utils/ssh.py: try to make failure to parse response more obvious

devlib/bin/scripts/shutils.in, devlib/module/sched.py
Add some new SchedModule APIs to get/set scheduler attributes and features.
=> Sched tunables

devlib/utils/ssh.py
As detailed in https://github.com/pexpect/pexpect/issues/552 when
sending a command with exactly the length of the prompt less than the
window width, an extra prompt is introduced into the returned data
causing the matching to fail and only return part of the commands
output. To workaround this check the length of the command to be
submitted and if of the specific length add an additional whitespace
character to the end of the command to prevent this behaviour.
=> utils/ssh: Implement work around for issue in pexpect

devlib/utils/android.py
Signed-off-by: Michalis Spyrou <michalis.spyrou@arm.com>
=> Add adb_server option in android background connection

devlib/trace/dmesg.py
Second round of fixes: it appears that versions of dmesg older than november 2017 do not support --force-prefix, so treat it like a the basic busybox dmesg and improve its support by parsing the raw log level. This may break on multi-line entries, but there is only so much we can do and parsing is opt-in, so it should not prevent basic users of the collector using it.
=> trace: dmesg: Allow using old util-linux binary

devlib/module/sched.py
Nothing too crazy here, mainly fixing some broken code I wrote.
This is adding some `info` logs on `SchedModule` probing, I can turn those into `debug` if needed.
=> Some SchedModule fixes/tweaks

devlib/utils/android.py
When executing a command using `su`, the `echo` command was returning the
error code of the invocation of `su` rather than the command itself.
Usually `su` should mimic the return code of the command it is executing
however this is not always the case which can cause issues.
=> utils/android: Echo the exit code of the actual command

devlib/target.py, doc/target.rst
Set LC_ALL=C by default before executing commands, so that commands have a predictable output.
Also some small fixes on PATH env var.
=> Set LC_ALL

devlib/module/cpuidle.py
Addresses https://github.com/ARM-software/devlib/issues/421
=> cpuidle: fix exist() --> exists() typo.

devlib/target.py, doc/target.rst
- Implements post initialised module installation. https://github.com/ARM-software/devlib/issues/412 
- Displays explicit message warning user upon module installation failure.
=> [RFC] Module installation improvements

devlib/trace/ftrace.py
Not all devices have the `saved_cmdlines_size` node exposed and therefore
attempting to set this will fail. Only attempted to set this if
this value is explicitly passed in.
=> instrument/trace-cmd: Do not set default for number of cmdlines

devlib/utils/ssh.py, doc/connection.rst
Signed-off-by: Michalis Spyrou <michalis.spyrou@arm.com>
=> Add options to ssh connection

devlib/instrument/daq.py, setup.py
daqpower 2.0 has a new interface and it is more stable.
=> daq: move to daqpower 2.0

devlib/target.py
Since bool is a subclass of int, turning 0 into False and 1 into True should not
break any user code.
=> target: Return a bool in Target.check_responsive()

devlib/utils/android.py
Update the entry for API level 28 and add an entry for API level 29.
=> utils/android: update SDK versions map

devlib/module/sched.py
While reading the DT-provided capacity values (exposed in sysfs) is
sufficient, get_capacities() also unconditionally fetches data from the
sched_domain procfs, which is only populated on kernels compiled with
CONFIG_SCHED_DEBUG.
Tweak the logic to only call get_sd_info() if it is both possible and
required.
=> module/sched: Fix get_capacities() on !SCHED_DEBUG kernels

devlib/utils/android.py
Ensure we use the `adb_server` parameter in adb helper functions.
=> adb server fixes

devlib/utils/version.py
Bump the development version due to the change in SSH interface.
=> utils/version: Bump dev version

devlib/target.py
Add property to AndroidTarget to retrieve the adb server if using an
AdbConnection and ensure this is passed in remaining adb_commands.
=> target: Propergate adb_server in all `adb_command`s

devlib/utils/android.py
[Original bug report](https://github.com/ARM-software/workload-automation/issues/1107#issue-640600414)
=> utils/android: Fix inconsistent logfile read mode

devlib/utils/version.py
Bump the version due to additional parameters exposed for transfer
polling.
=> fw/version: Development version bump

devlib/host.py, devlib/utils/misc.py
Fix issues highlighted from https://github.com/ARM-software/devlib/pull/509 
- Align the handling of stderr in `LocalTarget` to append to std output
- Fix bug in `LocalConnection` where stderr output was dropped unless output to stdout.
=> Fix LocalTarget and LocalConnection

devlib/collector/dmesg.py
Some kernels compiled with CONFIG_SECURITY_DMESG_RESTRICT can restrict
reading the dmesg buffer to root user as a security hardening measure.
Detect this case and use root accordingly.
=> devlib/collector/dmesg: handle CONFIG_SECURITY_DMESG_RESTRICT

devlib/module/sched.py
Recent kernels can have a space-separated list of textual flags rather
than a bitfield packed in an int.
=> modules/sched: Fix sched domain flags parsing

devlib/target.py, doc/target.rst
Use a Timer daemonic thread to cancel the command after the given
timeout.
=> target: Add Target.background(timeout=...) parameter

devlib/module/cpufreq.py
The cpufreq/scaling_* files reflect the policy configuration from a kernel
point of view. The actual frequency at which the CPU is running can be
found in cpuinfo_cur_freq. Warn when the requested frequency does not
match the actual one.
As the kernel does not provide any guarantee that the requested frequency
will be actually used (due to other part of the system such as thermal or
the firmware), printing a warning instead of raising an error seems more
suitable here.
=> module/cpufreq: Warn when cpuinfo doesn't reflect the cpufreq request

devlib/target.py, devlib/utils/misc.py
When Target.conn property is required while the current connection is
already in use, provide a fresh connection to avoid deadlocks. This is
enabled by the @call_conn decorator that is used on all Target methods
that use self.conn directly.
Fixes https://github.com/ARM-software/devlib/issues/528
note2: if we consider that:
1. we are not interested in passing Target methods as callbacks to connection methods
2. the impact of call_conn is negligible
then we could just apply it to all instance methods of Target automatically in a metaclass (or using `__init_subclass__` on Python >= 3.6) 
note 3: a new connection will be created for every decorated target method call that is done while a call to the connection is active. This this adds overhead, but since it only happens in exceptional …
=> target: Create new connection for reentrant calls

devlib/module/sched.py
Scheduler debug information is being unified under /sys/kernel/debug/sched
for Linux v5.13. Plug in awareness for the new path while still trying the
old one(s) for backwards compatibility.
Tested against v5.12 and upcoming v5.13-rc1 on a Juno r0.
=> modules/sched: Add awareness of new debug directory root

devlib/module/cgroups.py
Use shlex.quote() rather than "manual" quoting.
=> module/cgroups: Fix exclude pattern quoting

devlib/target.py
Remove references to non-existent dst_path_exists() function in
target.py
=> target: Fix undefined function

devlib/collector/dmesg.py
Rather than systematically clearing the buffer on reset(), record the
timestamp of the last entry and use it to filter-out old entries in
DmesgCollector.entries property.
This also allows detecting if the ring buffer has ran out of memory, or
if something has cleared the buffer while collecting, leading to missing
entries.
=> collector/dmesg.py: Allow nesting DmesgCollector

devlib/module/cgroups.py
Both move_all_tasks_to() and move_tasks() take a list of grep patterns
to exclude.
It turned out that move_all_tasks_to() was calling move_tasks() with a
string instead of a list, leading to broken quoting.
Fix that by passing the pattern list to move_tasks() and let
move_tasks() add the "-e" option in front of it. Also add a
DeprecationWarning in move_tasks() if someone passes a string instead of
an iterable of strings.
=> module/cgroups: Fix move_tasks()/move_all_tasks_to()

devlib/utils/android.py
With recent versions of adb, adb root can fail if the
daemon is already running as root.
Check the raised error message for this case and avoid
raising an error in this scenario.
=> android: Don't error if ADB is already running as root

devlib/module/cpuidle.py
Add support for listing the currently available idle governors and
setting the currently used one through sysfs.
=> module/cpuidle: Add listing & setting governors

devlib/exception.py, devlib/utils/android.py, devlib/utils/misc.py
This PR solves the freeze observed on some Pixel 6 root images when connecting to the target. The freeze appears to be related to some race condition in adb server when rooting/unrooting it.
Note that this PR needs a final round of validation on the actual device before being merged.
=> Fix adb root

devlib/target.py
The value for `max_async` when creating a target was being ignored
if a connection was not established as part of the __init__ method.
Save this value for use via `connect` if called directly.
=> target: Ensure max_async is used during `connect` method

devlib/host.py, devlib/utils/serial_port.py, devlib/utils/ssh.py
Fixes https://github.com/ARM-software/devlib/issues/525
=> Remove dependency on distutils

devlib/collector/perfetto.py
Use busybox cat instead of system's cat.
=> collector/perfetto: Use busybox cat

devlib/target.py, doc/target.rst
- [target: Fix indentation of a misaligned line](https://github.com/ARM-software/devlib/pull/659/commits/cb2945125a63084144525deb631f65a26f6037de)
- [target: Handle dozing case in checking Android screen state](https://github.com/ARM-software/devlib/pull/659/commits/50424e3f7567892ca2246ab89db030aa4e6c2182)
- [target: Add helper function to check Android screen's locking state](https://github.com/ARM-software/devlib/pull/659/commits/972c234804e3823dcf6ce87ce9bc673eceb67567)
=> target: Fix indentation of a misaligned line and groundwork for unlocking device screen

devlib/utils/android.py, devlib/utils/ssh.py
Fixes https://github.com/ARM-software/devlib/issues/660
=> Fix tool detection

devlib/utils/android.py
Change self.aapt into self._aapt
=> android: Fix typo in ApkInfo

devlib/target.py
Add a leading "/" so the path is absolute.
=> target: Fix read_sysctl()

devlib/__init__.py, devlib/collector/dmesg.py, devlib/collector/logcat.py, devlib/collector/serial_trace.py, devlib/collector/systrace.py, devlib/connection.py, devlib/host.py, devlib/module/cpufreq.py, devlib/platform/arm.py, devlib/target.py, devlib/utils/csvutil.py, devlib/utils/misc.py, devlib/utils/serial_port.py, devlib/utils/ssh.py, doc/connection.rst, doc/target.rst, tests/test_target.py
* ec006a0 - test_target: Add copyright statement
* be6dc8c - ChromeOsTarget: Fix building SSH connection parameter list
* f54bef0 - utils/ssh: Load host keys only if strict_host_check is true
* 34da9f9 - target: Customize as_root parameter of *write_value()
* 95f4a28 - devlib: Remove unused imports
* 121921f - devlib/init: Resolve pylint issues
* 586e340 - doc/connection: Fix typo Telenet
=> Bunch of fixes & improvements

devlib/utils/ssh.py, doc/connection.rst
Allow passing a known_hosts file path to strict_host_check.
=> utils/ssh: Allow passing known_hosts path via strict_host_check value

devlib/collector/dmesg.py
Check for all the CLI options we are going to use when deciding whether to use the system's dmesg or the one we ship via busybox.
=> collector/dmesg: Fix dmesg variant detection
