ARM-software/devlib

- devlib/module/cpufreq.py
These are a couple of patches which I've found useful especially on x86 machine with many cores.
They idea is to speed up the selection of multiple CPUfreq governors with just one single target-side command.
> CPUFreq: add some methods

- devlib/module/cpufreq.py
- devlib/trace/ftrace.py
This is a couple of simple patches which ensure to always get a trace with a complete description of the CPUs frequencies every time an experiment is executed while the "cpufreq" module is loaded.
Thus, for example, while running under "userspace" governor at a constant frequency, we always get a trace which has CPUs frequencies information.
> Add support to properly trace CPUs frequencies

- devlib/module/thermal.py
Add a thermal module that will allow querying for thermal zones and trip
points in the target. The module allow supports enable/disabling thermal
zones as well as change trip temperatures.
Signed-off-by: Punit Agrawal <punit.agrawal@arm.com>
> module: Add thermal support

- devlib/utils/android.py
In workload automation, utils.android._initialize_without_android_home()
gets android_home from adb's path.  When this code was copied to devlib,
we mistakenly dropped parsing the output of "which" and instead call
os.path.dirname() on "adb", which always returns "" and makes
_initialize_without_android_home() fail.
Make _initialize_without_android_home() parse the output of "which"
again.
> android: fix initialization without android

- devlib/instrument/__init__.py
When add channel for power meter with specific order, it also imply the
order with corresponding fields in captured data. So later need read
back the index for channel and use it to reference power data.
So need use ordered dictionary object for channel.
Signed-off-by: Leo Yan <leo.yan@linaro.org>
> Instrument: Add channel with ordered sequence

- devlib/target.py
When you create a target using devlib and pass a specific list of
modules that you want to use, failure to load one of them should be
reported as a warning instead of debug.
> target: warn if a module is not supported for the target

- devlib/utils/android.py
The ADB pull command allows only to pull a single file or a whole directory.
This patch adds the required support to pull only a selection of files, from
a target folder, which match a path specified using '*' and/or '?' wildcards.
In this case we first get the list of files on the target, using the
wildcard expansion support provided by the "ls" command, and than we pull
each and every file returned from the previous command.
This operation mode is available only if the 'dest' parameter is a valid
host-side folder.
> android: add support to pull multiple files using wildcard expressions

- devlib/trace/ftrace.py
The time required to fetch a trace depends not only on it time length but
also on the amount of events collected and the processing power of the
target device. This patch tries to factorise these last two components
into a 5x constant which is good enough to collect a relatively big trace
on a relatively slow device.
> ftrace: give more time for a trace to be collected

- .gitignore
- devlib/bin/scripts/shutils.in
- devlib/module/cpufreq.py
- devlib/target.py
Some interactive command on the target can be speed up by using a proxy script which runs entirely on the target and return a partially-processed result to the host.
This series introduces the idea to have a utility script deployed on the target which introduces a common base to run complex actions on the target. We use that script whenever we need to access multiple files to build an overall results. That way we can send just one command to the target, wait for one result and than (eventually) post-process that results to build host side python data structures.
The shutils script has been created to relay just on busybox command, thus it should be possible to execute it on all the target supported by devlib.
This script is the base to introduce an optimized support for some …
> Add shutils support

- devlib/bin/scripts/shutils.in
- devlib/trace/ftrace.py
NOTE: this series depends on the "add_shutils_support" series, actually the first three patches are from that series. Thus, merge it only *after* the shutils series has been accepted.
This series add support for kernel function profiling using FTrace.
The user can specify a set of functions to profile when ftrace is used.
The collection of results from different CPUs is accelerated using the shutils script to aggregate data from all the CPUs available in the system.
> Add ftrace function profiling

- devlib/target.py
`package_data_directory` and `external_storage_directory` are now arguments of AndroidTarget
fstab fixed for white space in paths
> AndroidTarget: Added package data and extrenal storage path settings and fixed fstab

- devlib/target.py
Not all devices have uname, since devlib deploys its own busybox binary
the most portable way to use uname is to use it via busybox.
> uname: Fixed calls to uname to use busybox

- devlib/module/cgroups.py
The info statements are clobbering the "normal" output of devlib users.
This patch demote the logging to debug level. The user can still
log-report these information from the corresponding functions call site.
> cgroup: demote info logging statement

- devlib/trace/ftrace.py
This series adds the support to have a single set of trace events and profile functions to be used with kernel which supports only some of these events. At FTrace initialization time we check which tracepoints/functions are available in the target kernel and enable only those. Not available tracepoints/functions are logged and reported to the user.
The first patch fixes a small bug related to trace marker injection.
> FTrace: optional function and events

- devlib/utils/ssh.py
Executing a command as root was not possible when running it in background.
This is done in a similar way as with a standard execute call.
This was also a bug in ssh.py because if you tried to run a background command
on the target, the background function in target.py was passing the as_root
parameter which was not present in ssh.py.
> ssh: add possibility to run command in background as root

- devlib/utils/android.py
The newline separator is a property of AdbConnection while the adb_shell is
just a method of the android module, thus we do not have a "self" pointer
to and AdbConnection from within the adb_shell function.
This patch fixes 8de24b5 by exposing the newline_separator used by adb_shell
as a parameter of that method and using the AdbConnection::newline_separator
to properly initialize it at executue() time.
> fix: AdbConnection: added automatic detection of new line separators

- devlib/bin/scripts/shutils.in
- devlib/module/cgroups.py
CGroups controller can be mounted by specifying a "noprefix" option, in which case attribute names are named according to this template:
<mountpoint>/<attribute_name>
instead of the (more recent) naming schema using:
<mountpoint>/<contoller_name>.<attribute_name>
For example, Android uses the old format for backward compatibility with user-space. Thus, it's possible in general to work on a target system where some controller are mounted "noprefix" while others not.
This patchset adds a set of updates which allows to use the proper attributes naming schema based on how the controller has been mounted.
> Fix cgroups noprefix

- devlib/target.py
kick off will now use root if the device is rooted or if manually
specified otherwise its run without root.
> AndroidDevice: kick-off no longer requires root

- devlib/module/cgroups.py
- devlib/target.py
Shutil scripts requires a valid busybox path which is defined after a call to setup().
This series adds a new "setup" stage for modules initialization, which is executed once the setup() function completed. This stage is used by the cgroups module which requires some shutil functions at initialization time.
> Cgroup fix setup

- devlib/target.py
To install busybox we need to know the ABI of the device to push the
correct binary but to know the ABI we need busybox.
Since uname is part of the POSIX standard and this issue only effects
the LinuxTarget (AndroidTarget gets this from build.prop) it is safe
to assume all LinuxTargets should have uname.
> LinuxTarget: now used 'uname' instead of 'busybox uname'

- devlib/utils/misc.py
- setup.py
Using the wrapt module we can improve the memoize decorator. In fact, it allows
to preserve the attributes of the memoized function, such as signature,
docstring, path to the file where the function is implemented, and so on.
Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>
> Improve memoize decorator

- devlib/utils/android.py
The "adb connect" command is required only for USB connected devices.
This patch is a small update which avoid the connect for non IP accessed
devices.
> android: avoid connect for USB target

- devlib/module/cpuidle.py
When passing an idle state ID to get_states(), nothing is returned. Also, there
is a wrong call to enable() in the method.
Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>
> cgroups: fix get_states() return value when passing integer state

- devlib/bin/scripts/shutils.in
- devlib/module/cgroups.py
This series adds some fixes for the CGroup module and a couple of new functionalities:
- isolation: which allows to isolate a specified list of CPUs by moving all tasks in the remaining CPUs
- freezer: which allows to freeze all the tasks of the target
Both functions accept a list of tasks to exclude. Excluded tasks are keept in the root CGroups thus:
- they can run on isolated CPUs
- they are not frozen
@mdigiorgio can be interested in reviewing/testing these functions, since they should be useful for its energy-model building flow ;-)
> Add support for CPUs isolation and tasks freezing

- devlib/utils/android.py
Just a tiny problem here, but it is preventing me from using Juno over tcpip :)
If you try to disconnect a device and there are none, certain versions
of adb return 1, which leads to a TargetError and stops everything in
its tracks.
Try to mitigate this by checking if the device we want to disconnect is
connected before we make the disconnect call.
> android: don't try to disconnect devices which aren't connected

- devlib/module/cpufreq.py
Currently when using set_all_governors to try to set an unsupported
governor, the error is a somewhat cryptic "sh: echo: I/O error". Add a
check that diagnoses this error.
In order to avoid slowing down the "good" path, the check for
unsupported governors is only done if the failure has already occured.
> cpufreq: Improve error when setting all CPUs to unsupported governor

- devlib/module/cpuidle.py
When this information is not needed, this avoids executing 4 commands on
the host for each CPU, which significantly speeds up initialising the
cpuidle module.
> cpuidle: Make desc, name, latency, power memoized properties

- devlib/utils/android.py
When using 'check_exit_code' and 'as_root' options for adb_shell with
a command containing single quotes, the provided command was escaped
twice. The second escaping has been avoided and some unit tests added
to check functionality.
> android: Fixed issue using single quoted command with adb_shell

- devlib/bin/scripts/shutils.in
- devlib/module/cpuidle.py
- devlib/trace/ftrace.py
On some systems CPUs sometimes remain idle for several seconds. If a
trace capture begins during one of these long idle periods, that CPU's
idle state is unknown (in practice it is probably in its deepest
available state from cpuidle's perspective but that can't be known for
sure).
The solution to the equivalent problem for cpufreq is to read the
current frequencies from sysfs and inject artificial cpu_frequency
events using trace_marker (see cpu_freq_trace_all_frequencies in
bin/scripts/shutils.in). However we can't read the current idle state
from sysfs.
Instead, wake up each CPU by executing the "true" command on it via
taskset.
> ftrace: Poke all CPUs before collecting trace

- devlib/module/cgroups.py
Some systems mount CGroups RO, thus we need to ensure we remount that
FS as root otherwise we cannot create new groups.
> cgroups: ensure CGroups are mounted RW

- devlib/bin/scripts/shutils.in
- devlib/module/cgroups.py
An assortment of fixes for cgroups.py and shutils. CC @derkling 
Not fixed: "CgroupsModule::freeze(exclude=['sh'])" will also not freeze any process with "sh" in the comm so `sshd` etc will not be frozen.
> Fixes for cgroups

- devlib/utils/android.py
I have observed that when there are multiple matches for the wildcard, `line` has a space at the end. That means the `pull` command doesn't work.
> android: Fix whitespace in wildcard match for ADB pull

- devlib/target.py
I can't get sphinx to build the docs to check if this is the right syntax.. it feels too trivial to spend any more time on so feel free to just close this if it looks wrong.
> target: Note return value in Target::invoke docstring

- devlib/bin/scripts/shutils.in
The injection of a fake cpu_frequency event in the trace may end up getting
interleaved with trace events generated by the cpufreq governor, for example:
sh         ... cpu_frequency: state=120000 cpu_id=0
kschedfreq ... cpu_frequency: state=120000 cpu_id=0
kschedfreq ... cpu_frequency: state=120000 cpu_id=1
kschedfreq ... cpu_frequency: state=120000 cpu_id=2
kschedfreq ... cpu_frequency: state=120000 cpu_id=3
sh         ... cpu_frequency: state=120000 cpu_id=1
sh         ... cpu_frequency: state=120000 cpu_id=2
sh         ... cpu_frequency: state=120000 cpu_id=3
Such a trace may confuse trace parsers during postprocessing and lead to wrong
or no results.
This patch renames the events injected by devlib so that they can be easily
recognized and then used by the trace parser in the best …
> shutils.in: rename manually injected cpu_frequency trace event

- devlib/target.py
Use case: To check if a kernel supports function profiling we need to
check for the presence of
"/sys/kernel/debug/tracing/function_profiler_enabled", but
"/sys/kernel/debug/"'s permissions are 700.
> target: Use root in file_exists check

- devlib/bin/scripts/shutils.in
If a process is added to $PIDS but then exits before the
cgroups_task_move invokation finishes, then echoing its PID to
cgroups.procs results in an I/O error. If that process is the last in
$PIDS, then that failing echo command is the last of the function, so
the script exits with an error and devlib raises an exception.
Add `|| true` to avoid this problem.
---
CC @derkling
> shutils/cgroups: Don't fail when racing with process exit

- devlib/bin/scripts/shutils.in
- devlib/module/cgroups.py
Here is a series of modifications which introduce the support for multi-controller hierarchies to the CGroup module. This support is requires whenever we want to use CGroups in a system which has already some controllers mounted together in a single hierarchy, which is a quite common case.
This series fixes also some errors introduced in previous patches regrading the execution of a workload under a specified cgroup.
> Cgroups multi controller

- devlib/host.py
This parameter is used by the other connection classes and as of
21f40035d785 ("gem5: Small tweaks in target to allow gem5 simulations") is
passed by to the connection class constructor via expansion of
Target.connection_settings (see Target.get_connection)
---
Relevant code [here](https://github.com/ARM-software/devlib/commit/21f40035d785950c439a77303b162940978e6fac#diff-ace949208afde1948ca24e3746a5e425R170) and  [here](https://github.com/ARM-software/devlib/blob/21f40035d785950c439a77303b162940978e6fac/devlib/target.py#L215)
> LocalConnection: Add ignored `platform` param to __init__ method

- devlib/target.py
This adds a regexp to better parse all the kernel version numbers as well
as additional (optional) fields like SHA1 and RC.
The regexp has been made generic enough to match these examples:
4.9.0-rc6-00202-g3a60597
4.9.0-rc6-00202
4.9.0-rc6-00202-g3a60597 #321 SMP PREEMPT Mon Feb 13 12:30:59 GMT 2017 aarch64 GNU/Linux
3.18.31-g226dafe #1 SMP PREEMPT Wed Feb 15 16:34:14 GMT 2017
4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017
3.11.0-26-generic #45~precise1-Ubuntu SMP Tue Jul 15 04:02:35 UTC 2014
3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016
3.13.0-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016
4.8.0 #1 SMP Fri Jan 6 18:06:24 GMT 2017
> target: better parse kernel version numbers

- devlib/target.py
- Make the numerical fields `int`
- Add a `parts` field. tuples are nice for this in that e.g. `(4, 8, None, 5) > (4, 7, 3, 0)` so it can be used for comparison. I thought about adding a `__cmp__` but it seems a bit hairy as it would break using `KernelVersion` as a dict key.
- Docstring \o/
> Fixup KernelVersion API

- devlib/target.py
When rebooting a platform the internal connection state becomes
different from _connected_as_root, which was set before reboot.
Add the possibility to force adb root if you've rebooted or know
to have done something that would result in the platform having
a different connection state than the one of _connected_as_root.
> android: add support for forced adb root

- devlib/utils/android.py
If the ADB command fails (e.g. if you provide the wrong device ID), adb_command
raises a CalledProcessError. CalledProcessError doesn't print the output of the
failed command, so you get a useless error message.
This is relevent here in particular as _setup_ls is the first thing to run an
ADB command if a non-IP device ID is provided.
Catch the CalledProcessError and instead raise a HostError with the command
output in the exception message.
> android: Improve error when _setup_ls fails

- devlib/target.py
From #92, when rebooting a platform the internal connection state becomes
different from `_connected_as_root`, now clears the state upon device reboot or
reset.
> Target: Invalidates _connected_as_root on reboot or reset.

- devlib/module/cpufreq.py
Fixes issue #98 where the passed `cpus` parameter was ignored when setting the
governor and frequency and set for all cpus instead of those specified in the
passed parameter.
Also fixes kwargs not being correctly passed for governor tunables.
> cpufreq: Fixed set_x_for cpus

- devlib/instrument/energy_probe.py
This means when caiman is broken you can see the error message, instead of just
finding out later that there is no data.
We still don't detect caiman being broken until we call stop(), but it's still
an improvement.
> energy_probe: Check if caimain was broken and raise an error

- devlib/target.py
As per issue #102, not all devices have permission to list the root directory
causing the ls command to be incorrectly determined. This commit changes the
directory to be checked to the working directory to ensure sufficient
permissions.
> Target: Fixes __setup_list_directory issue on production devices.

- devlib/module/cpufreq.py
`cpu` can be an `int`, _or_ the full CPU name used by sysfs.
> cpufreq: Fix docstring for `cpu` parameter

- devlib/module/cpufreq.py
If we get an TargetError when trying to set a governor tunable we currently fall
back to an older sysfs layout under the assumption that the file we tried to
write doesn't exist. However it may be that the file exists, but we tried to
write an invalid value (or something else went wrong). In this case we fall back
to the old file location, fail, and produce a nonsense error about the old path
not existing.
Instead, when we get a TargetError, check if the file exists, and fall back to
the old location only if it does not.
> cpufreq: Expose error when writing invalid governor tunable

- devlib/target.py
Targets have been observed where `ps` output contains entries with NAME columns
of the form "[foo bar]". This means the `parts` list is too long and the PsEntry
call reports too many arguments. Since NAME is the rightmost column, just fix
the number of entries we recognise to 8.
> AndroidTarget: Fix `ps` when NAME column contains spaces

- devlib/target.py
On some devices backgrounding a task results in the command returning
immediately with no error. This was falsely interpreted as the command failing
to run, therefore the additional check has been removed.
> Target: Stopped `kick_off` raising an error if command didn't timeout

- devlib/bin/scripts/shutils.in
This can currently take several hundred milliseconds on slow targets with many
CPUs. To speed it up, use '&' to spawn the perturbations in paralell.
> shutils: Speed up cpuidle_wake_all_cpus

- devlib/target.py
Previously trying to pull a file from an android target would fail if the file
was owned by root, this commit adds read permissions to the file before
attempting to pull.
> Target: Add read permissions to tmp files before pulling

- devlib/instrument/__init__.py
- `Instrument.channels` is a dictionary, we want the values not the
keys; this is provded by `list_channels`.
- `InstrumentChannel` objects do not have a `measure` attribute. Use
`kind` instead.
> instrument: Fix get_channels method

- devlib/instrument/__init__.py
- devlib/instrument/daq.py
- devlib/instrument/energy_probe.py
- devlib/platform/arm.py
- doc/instrumentation.rst
Don't have a DAQ so couldn't test that. Also couldn't get the Juno readenergy.c instrument working on my board. Decided that this can't really break anything, though.
> Add sample_rate_hz attribute to CONTINUOUS instruments

- devlib/__init__.py
- devlib/instrument/monsoon.py
This adds support for the Monsoon Power Monitor:
https://www.msoon.com/LabEquipment/PowerMonitor/
This device officialy supports only MS Windows so we use a tool from AOSP to
communicate with it from Unix targets:
https://android.googlesource.com/platform/cts/+/master/tools/utils/monsoon.py
The user is required to install this tool and its dependencies, then pass the
path to it as the monsoon_bin parameter.
> instrument: Add support for Monsoon Power Monitor

- devlib/utils/ssh.py
Previously, the flag was not propagated, so the error code was always
checked. With this change, we propage it to the _gem5_shell method.
> Propagate check_error_code

- devlib/target.py
- doc/target.rst
It sometimes can be useful to enable dry-run before calling
high-level functions in order to check what individual commands
are being called (or do whatever else with them).
This patch adds dry-run with an on/off switch:
once start_dryrun() is called, every subsequent command passed to
execute() will be accumulated in a list. stop_dryrun() returns that
list and disables dry-run.
> target: add dry run for command execution

- devlib/target.py
- doc/target.rst
Reverts ARM-software/devlib#127
Following further discussion (see pull request thread), it was decided that this functionality shouldn't be in devlib in its current form.
> Revert "target: add dry run for command execution"

- devlib/instrument/energy_probe.py
ARM energy probe sends SIGTERM to caiman, this signal can be missed by
caiman due caiman has not registered signal handler for SIGTERM. On the
other hand, caiman registers signal handler for SIGINT, this patch is to
change to use signal SIGINT to notify caiman.
Signed-off-by: Leo Yan <leo.yan@linaro.org>
> energy_probe: send signal SIGINT to caiman

- devlib/module/cpufreq.py
I have observerd the error message "write error: Invalid argument"
when using set_all_governors to set a non-existent governor on a
buildroot Linux system
> cpufreq: Add possible error message for failing to set governor

- devlib/target.py
- doc/target.rst
I find it useful to launch several tasks and pin each of them to a specific cpu. The implementation is trivial, maybe a separate invoke_bg method with the `timeout` parameter would be preferred ?
> Add option to run target.invoke() in the background

- devlib/module/gem5stats.py
- devlib/utils/gem5.py
Gem5's statistics log file contains plenty of interesting information
that are not exposed so far. This module enables control and parsing of
the statistics file by:
- configuring periodic dumps of statistics;
- marking Regions of Interest (ROIs);
- and extracting values of specific fields during the ROIs.
> module: Control and parse gem5's statistics log file

- devlib/utils/misc.py
Update the MIDR CPU part number table with values from
https://github.com/torvalds/linux/blob/master/arch/arm64/include/asm/cputype.h
> utils/misc: update MIDR table

- devlib/utils/misc.py
> misc.py: fix syntax error introduced by 86c9b6a1c7e

- devlib/utils/android.py
Include the stdout/stderr output in the message of the exception raised
when the exit code of the adb command cannot be detected.
> utils/android: better error message when exit code not detected

- devlib/module/thermal.py
Calling thermal.disable_all_zones() would raise an exception.
I've changed a few things:
* use self.zones.itervalues() in disable_all_zones to fix that exception
* renamed zone.set_mode() to zone.set_enabled()
> devlib/module/thermal: Fix thermal zone disabling

- devlib/module/cpufreq.py
- devlib/utils/android.py
Allow the user to specify where the ADB server is located: in some cases the Android devices might be connected to a different machine. (See -H option: https://developer.android.com/studio/command-line/adb.html )
However, usually the ADB server runs on the same machine as the ADB client therefore the default value for the server is 'localhost'
> Add support for arbitrary ADB servers

- devlib/instrument/gem5power.py
- devlib/module/gem5stats.py
Currently, reset_origin() in the gem5stats module enables to virtually
truncate the existing dumps from the gem5 statistics file so that any
subsequent match() calls will apply only on new dumps. However, the
current implementation resets the origin of the stats file unilaterally,
without other clients knowing about it, hence leading to data being
lost.
This commits removes the reset_origin() method and provides a different
API to handle virtual truncatures in the stats file. Namely, the match()
method now takes a base_dump parameter letting clients specifiying from
which dump they want match() to apply. This feature could also be usefull
if someone wanted to add off-line processing features for statistics
files.
> module/gem5stats: enable asynchronous origins in gem5 stats file

- devlib/bin/scripts/shutils.in
- devlib/module/cgroups.py
The `set()` method of the CGroup class used to freeze tasks relies on target's `write_value()`. Sometimes, the freezing procedure takes some time and the call to `write_value()` in `set()` fails by reading `FREEZING` while it expected `FROZEN` (reported in issue #136). To avoid this issue, this PR allows `write_value()` to retry the check several times before raising an exception.
> module/cgroups: robustify task freezer

- devlib/instrument/gem5power.py
- devlib/module/gem5stats.py
- devlib/utils/gem5.py
The current implementation of match() in the gem5stats module returns
records matching exactly the specified keys. This PR changes this
behaviour by matching keys over regular expressions, hence resulting in
a much more powerful match() implementation.
> module/gem5stats: enhance match() with regex support

- devlib/target.py
- devlib/trace/logcat.py
- devlib/utils/android.py
The code could probably do with some cleanup, but I wanted to get some feedback before investing too much time into it.
This was made due to a need to parse logcat with lines that can come out of order. Furthermore, most of the logcat parsing done in LISA was copy-pasted from one workload to another, so I wanted to centralize that.
The idea here is to have a thread that reads from logcat, and it can also look for certain regexps (by default '.*', so every line will be logged). We can then search for all the lines matching a given regexp. The general use case is:
```
my_regexps = [...]
logcat = target.logcat_monitor(my_regexps)
logcat.start()
my_workload.run()
logcat.search(WORKLOAD_START_REGEXP)
print "workload started !"
logcat.search(WORKLOAD_END_REGEXP)
print "workload ended !" …
```
> Logcat monitor

- devlib/host.py
This method is useful for killing the children spawned by Popen() calls with shell=True. For instance:
```
proc = Popen('sleep 100', shell=True)
proc.kill()
```
This would spawn a shell task and that shell would spawn the sleep task.
Issuing a kill to the Popen handle will only kill the shell task, and the sleep task will keep running.
Using `host.kill_children(proc.pid)` will ensure all child tasks are killed.
> host: Add kill_children utility method

- devlib/utils/android.py
This is mostly useful to avoid having to manually click/tap on the permission requests that may pop up when opening apps, which would ruin automation
> utils/android: Add grant_app_permissions

- devlib/instrument/__init__.py
- doc/instrumentation.rst
- Fix missing parameter in the documentation
- Clarify meaning of `sites` and `kinds` in the documentation.
- With the current implementation the `channels` argument is
useless: if `sites` and `kinds` are not also specified then all
channels are enabled anyway. Fix that by making those parameters
ignored when `channels` is provided.
> instrument: Clear up Instrument.reset semantics

- devlib/utils/android.py
Otherwise if the server isn't started we fail to parse the output of
'adb devices'
> utils/android: Start ADB server before listing devices

- devlib/utils/android.py
I wrote an extension for the logcat monitor to be able to wait for multiple regexps at once using `pexpect.expect`, but it turned out to be unnecessary. 
However in the process I wrote some docstrings, so might as well throw them in.
> utils/anroid: Documentation for LogcatMonitor

- devlib/module/hwmon.py
If we don't have permissions, scan() currently raises a
TargetError. Instead we should return False from probe() so the
module is disabled
> hwmon: Disable if no permissions

- devlib/bin/scripts/shutils.in
- devlib/module/__init__.py
- devlib/module/cpuidle.py
- devlib/module/hotplug.py
- devlib/module/hwmon.py
- devlib/target.py
- doc/target.rst
This pull request contains a number of module initialization optimizations that
significantly reduce the time it takes to start a new run. Testing with a
USB-connected Android device, the time for a run of a single uninstrumented
dhrystone  was reduced from ~75 to ~20 seconds.
This reduction is a achieved by reducing the number of calls that need to be
made to a target in order to initialize module state. This done by introducing
APIs for extracting values from an entire sysfs sub-tree  in a single call.
> Module initialization optimizations.

- devlib/bin/scripts/shutils.in
read_tree_values and hotplug_online_all relied on () array evaluation
which is a Bash thing and is broken in sh; this fixes things for sh.
> shutil: fix read_tree_values and hotplug_online_all for sh

- devlib/bin/scripts/shutils.in
The previous fix for read_tree_values fixed the issue with sh not
supporting arrays, but looping over paths and counting them. Hover each
count increment requires spawning a subshell. For a large number of paths,
this can eat away any performance benefits of using read_tree_values.
Since we only care whether the count is greater than one, detect that
and break out of the loop early to re-introduce the performance
improvement.
> shuilt: re-introduce speedup

- devlib/target.py
Due to the new read_tree_values API, some devlib modules now use
shutils in their __init__, which happens from
Target::connect(). Therefore ensure we have busybox on the target
before we get to that stage.
> target: Install busybox before updating modules

- devlib/target.py
'adb logcat -c' has been observed to fail when called twice concurrently. Rather
than requiring all devlib users to fix their usage patterns, let's just delay
whenever clear_logcat is called twice.
> AndroidTarget: prevent concurrent invocations of 'logcat -c'

- devlib/utils/android.py
Provide a more specific error, including the output from aapt.
> ApkInfo: Improve error for bad .apk files

- devlib/utils/misc.py
- devlib/utils/ssh.py
Fix gem5 implementation of pull() to properly strip ANSI sequences from the result of running 'ls' internally. Also expand the number of sequences that get stripped.
> ANSI escape sequences stripping fixes for gem5

- devlib/target.py
Recently I've been seeing some errors with enabling airplane mode on
hikey960 - firstly I get a 'broken pipe' error followed by a 'cmd:
Can't find service: settings'. This missing boolean was the first
thing I found that had changed wrt. the code I used to use, and
adding it back appears to fix the issue.
> AndroidTarget: Add boolean 'state' to airplane mode intent broadcast

- devlib/utils/android.py
I wrote this for another reason which turned out not to be necessary. However it turns out that the current LogcatMonitor can't be killed with Ctrl+C while it's in the `threading.Event.wait` in `wait_for`, which is irritating. So I'm submitting this now. It also reduces lines of code which I guess is Good.
> android: Use pexpect for LogcatMonitor

- devlib/instrument/acmecape.py
Once an ACME cape instrument is released, if the stop() method has not been called by the client code, let's ensure to release the channels by killing the corresponding iio-caputure process.
> Instrument/Acmecape: ensure iio-capture termination

- devlib/target.py
That means you can pass the result back to set_rotation without
having to change its type.
> AndroidTarget: Make get_rotation return an int

- devlib/module/gpufreq.py
Add a module for controlling and interacting with GPUs. The module
currently supports kgsl/adreno based GPUs. This allows for querying
and setting the governor on the GPU, as well as seeing the frequencies
at which the the GPU can can operate.
Change-Id: I02bb997b51426ddaa13e1f8da375aa4c4a0d341a
> module: add a gpufreq module for interacting with GPUs.

- devlib/bin/scripts/shutils.in
When running a command into a cgroup we want to make sure that the command is
only run inside the intended cgroup. If there is a hierarchy of cgroups named
with a common prefix, the script will move it to all matching cgroup and as a
result the task will end up running always at lowest level. For example, if we
have the following hierarchy of cgroups:
````
"/"
|__ "/tg1"
|__ "/tg1/tg1_1"
````
and we want to run something in cgroup "/tg1/", the lowest levels will match the
regexp and the task will ultimately be moved to "/tg1/tg1_1".
This patch fixes the issue by requiring the absolute path of the specified
cgroup to match exactly.
> shutils: look for an exact match of a cgroup

- devlib/target.py
In an effort to reduce thrashing, "implicit" broadcasts are no longer
allowed in Android O. See:
https://issuetracker.google.com/issues/36496703#comment7
This impacts MEDIA_MOUNTED broadcasts. To get around this issue,
explicitly specify the component the broadcast is targeted at.
> target: fix broadcast_media_mounted for Android O

- devlib/derived/fps.py
Avoid dividing by frame_count if it's zero when calculating janks_pc.
> derived/fps: fix divide by zero

- devlib/platform/gem5.py
m5 binaries are not properly versioned, so it is not possible to be sure
that the one that is already present on the image has all the features
needed by devlib. Thus always deploy and use our version.
> platform/gem5: always deploy m5 binary

- devlib/target.py
Fix for Chromebook Plus and possibly other devices - removes forbidden
characters from the device_model such as the null character.
> LinuxTarget: Port forbidden char fix from WA2

- devlib/instrument/gem5power.py
active_sites is used instead of sites_to_match and that
results in "KeyError: 'timestamp'" when parsing the
statistics file. 'sim_seconds' should be used instead
of 'timestamp'.
> gem5power: fix gem5power get_data after channel rename

- devlib/module/cpuidle.py
Remove a stray debug print which was accidentally committed.
> module/cpuidle: remove stray print

- devlib/instrument/__init__.py
Channel labels can contain punctuation which is not accepted in
Python identifiers.
> instrument: convert channel labels to valid Python identifiers

- devlib/utils/android.py
Previously the root directory was used when checking for device
connection, on some devices this requires elevated permissions so now
use '/data/local/tmp' which should not have permission restrictions.
> utils/android: Change directory used for checking connection

- devlib/target.py
Since 1e34390b990f1d85b083d31693d71fad5c9f28a6, AndroidTarget and
LinuxTarget share the same code for `push` and `pull`. However,
these methods expect a `_file_transfer_cache` field to be present.
It is currently populated in `_resolve_paths` for AndroidTarget
and LinuxTarget, but not for LocalLinuxTarget.
Since LocalLinuxTarget inherits its `push` & `pull` from LinuxTarget,
this causes an exception. This commit fixes it by adding an assignment
to `_file_transfer_cache` in `LocalLinuxTarget:_resolves_paths`.
This is a simple fix, and the actual push/pull behaviour of that local
target class could be improved in regards to that transfer cache, but
it should be good enough for now.
> target: LocalLinuxTarget: Populate _file_transfer_cache

- devlib/target.py
Do not attempt to create shutil from shutil.in inside
PACKAGE_BIN_DIRECTORY as that may not be writable. Instead, create it in
the temporary directory and remove it right after installing.
> target: do not create shutil in package directory

- devlib/target.py
Previously, the default timeout was 10s which is too short in some cases.
> target, android: Set the default timeout to 30s

- devlib/platform/gem5.py
Point to gem5's stderr file in the message of the error raised on crash
during _intercept_telnet_port.
> platform/gem5: better error message on crash

- devlib/target.py
Since:
cafc0a4 target: do not create shutil in package directory
we generate 'shutils' in /tmp, which is also the executables_path
used used by deafult by a LocalLinuxTarget.
This ultimately results into a:
self.install(shutils_ofile)
...
shutil.copy(source, dest)
raising an exception since source == dest.
Let's fix this by setting /tmp/devlib-target as a default base path for
all devlib deployed stuff into a localhost target.
> LocalLinuxTarget: fix executables folder location

- devlib/target.py
Previously the same temporary directory was used which caused issues
with concurrent runs interfering with each other.
> Target: Generate a new tmp directory when creating shutils

- devlib/utils/misc.py
Now ensures that the given text does not start with a digit and if so
prefix an underscore to ensure a valid python identifier.
> utils/misc: Check if identifier starts with a number

- devlib/target.py
Some targets don't seem to set system.user_rotation, resulting in "null"
being returned. This exploded on integer conversion. Handle this case by
returning the Python equivalent, None.
> target: fix get_rotation() when null

- devlib/trace/ftrace.py
Double the existing timeout, as the current one is too short for noisy
devices on slower connections.
> trace/ftrace: increase trace pull timeout

- devlib/utils/misc.py
string.translate can fail when passed a unicode object; explicitly str()
it first to avoid this.
> utils/misc: fix to_identifier for unicode

- devlib/module/cgroups.py
Fix cgroups tasks parsing in Controller.tasks() method, to ignore lines
that are not formatted properly.
> cgroups: fix Controller.tasks()

- devlib/platform/gem5.py
gem5 prints a string, to communicate which telnet port can be used to connect
to the gem5 system.  The exact string has recently changed. This commit ensures
both the old and new string are taken into account when devlib parses gem5
output to determine the telnet port.
> gem5: Update to telnet connection method

- devlib/derived/energy.py
Correctly detect whether or not the energy should be calculated from
power or extracted directly. Previously both methods were being used
at the same time, resulting in incorrect total energy values.
> derived/energy: Fix energy calculation

- doc/target.rst
Updated documentation for capture_screen with the information about the
optional timestamp format tag.
> doc: document capture_screen timestamp

- devlib/trace/screencapture.py
Add a poller which takes a screenshot at a configurable interval
(`period`). Files are named based on the device timestamp, and are
placed into a configurable output directory.
> trace: Add screencapture

- devlib/module/cpufreq.py
Add a method to read the name of the driver for cpufreq policy for a
cpu.
> cpufreq: add missing get_driver() method

- devlib/target.py
Previously the path for listing a directory on the device was not quoted
causing it to fail on paths containing spaces. Now ensure the string is
quoted and any quotes contained in the string as escaped.
> LinuxTarget: Ensure path is correctly quoted when listing directories

- devlib/target.py
Previously the path for listing a directory on the device was not quoted
causing it to fail on paths containing spaces. Now ensure the string is
quoted and any quotes contained in the string as escaped.
> AndroidTarget: Ensure path is correctly quoted when listing directories

- devlib/module/cpuidle.py
Ensure that cpuidle.get_states() always returns a list, even if no idle
states are available on the target.
> module/cpuidle: ensure get_states() returns a list

- devlib/module/cgroups.py
On latest hikey960 android image, only root can execute: cat /proc/cgroups
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
> cgroups: add execute as root

- doc/modules.rst
Adds documentation for the previously added methods in commit
a1e58cd8b1b293d5a18f204effbe1f37efcbecd4
> doc/cpufreq: Add docs for max/min frequency methods.

- devlib/module/cpufreq.py
Check /sys/devices/system/cpu/cpufreq/policy0 rather than its parent
during the probe. This is to handle the edge case where cpufreq has
been enabled in the kernel, but no frequency domains have been defined
(in which case, the module should not install).
> module/cpufreq: include policy0 in probe path

- devlib/utils/android.py
Previously if a device was connected over usb then the adb_connect
method would assume the device was already connected. This can cause
issues when rebooting and the device is not ready by the time devlib
attempts to reconnect to it causing the next command to fail. Now still
only execute the 'connect' command when the device is connected over the
network, however always trying pinging the device to see if it is
connected before returning.
> utils/android: Try to ping adb devices regardless of connection type

- devlib/__init__.py
- devlib/trace/serial_trace.py
- devlib/utils/serial_port.py
We add a TraceCollector which logs the traffic on a serial port. This
can then be used to debug why a board crashes, or to extract extra
information from the device whilst it is running a workload.
> trace/serial_trace: Add capability to trace serial traffic

- devlib/platform/arm.py
- devlib/utils/misc.py
Convert bytes to strings (utf-8 encoding) to make compatible with
Python3 in arm.py
Drop problematic characters when decoding stdout and stderr in misc.py
by setting errors='replace' in the string decode method.
> Fix Python3 Byte Handling

- devlib/trace/serial_trace.py
We add a missing flush which esures that all data has been synced to
the temporary file before we copy it. Prior to this commit, we would
sometimes miss the last few lines of the trace.
> trace/serial_trace: Flush data to file before copying

- devlib/utils/android.py
- devlib/utils/misc.py
Make sure target.execute() includes the command's stderr in its output on both
Linux and Android.
> Align stderr handling across Linux and Android

- devlib/module/sched.py
- devlib/target.py
This module is a collection of scheduler data getters.
There's quite a few places in LISA where we re-implement these (mostly capacity getters), so I figured this would be the best place to bunch it up.
I'm a bit conflicted about the handling of the EAS energy model - we have a ~1000 line file that handles everything energy model related, and some of it could be moved here. However I don't think it's a simple task, so for now the handling of energy model data done in this module is trivial.
Also, I should make sure this runs fine on Python3 to get it in line with the other modules, but I figured I could collect some comments first :)
> module: Add sched module

- devlib/utils/types.py
This should have been handled by the @total_ordering decorator, but
isn't due to
https://bugs.python.org/issue25732
(briefly, total_ordering is back-ported from Python 3, where the base
object provides the default implementation of __ne__ based on __eq__, so
total_ordering did not override it; this, however does not happen in
Python 2).
> utils/types: implement __ne__ for caseless_string

- devlib/bin/scripts/shutils.in
- devlib/module/devfreq.py
Add support for devfreq. This is used for example to get/set the frequency
and/or governor of the GPU.
> module: Add devfreq module

- setup.py
When installing from source devlib attempts to include the commit ID in the
version of the installed pacakge however this caused issues with package
managers like pip. PEP440 specifies that local identifiers must be in the
form `<public version identifier>[+<localversion label>]` so update the
version to conform.
https://www.python.org/dev/peps/pep-0440/#local-version-identifiers
> setup.py: Change format of version to conform with PEP440

- devlib/target.py
Use convert_new_lines() before stripping out '\n' character from OS
version strings to ensure no stray '\r's are left in.
> target: fix new line handling in os_version

- devlib/utils/misc.py
If the process was killed, either the output or error can
be `None` which causes an error when attempting to join the outputs.
> utils/misc: Ensure outputs are converted to strings

- setup.py
Add -s flag to sdist command, which, when used, strips away the git
commit hash from the package version. This is needed for upload to PyPI.
> setup.py: add -s flag to sdist

- devlib/utils/version.py
Check that the resulting output inside get_commit() is a str before
attempting to decode it when running on Python 3.
> utils/version: do not decode bytes

- doc/overview.rst
Mention ChromeOsTarget when listing available target types in the
overview.
> doc: mention ChromeOsTarget in overview

- devlib/utils/misc.py
Default to assuming 'utf-8' encoding for environments where
sys.stdout.encoding is not set.
> utils/misc: check_output: handle unset sys encoding

- devlib/module/cgroups.py
The shutils run_into support assumes that we always specify a full
cgroup path starting by "/". If, by error, we specify a cgroup name
without the leading "/" we get an ambiguous message about the cgroup not
being found.
Since this already happened to me many times, let's add an explicit
check about the cgroup name parameter to better info the user about the
requirement.
> cgroups: explicitly check for proper CGroup naming

- devlib/__init__.py
- devlib/exception.py
- devlib/host.py
- devlib/instrument/gem5power.py
- devlib/instrument/hwmon.py
- devlib/instrument/netstats/__init__.py
- devlib/module/cgroups.py
- devlib/module/cpufreq.py
- devlib/module/devfreq.py
- devlib/module/gem5stats.py
- devlib/module/gpufreq.py
- devlib/module/hwmon.py
- devlib/module/vexpress.py
- devlib/platform/arm.py
- devlib/platform/gem5.py
- devlib/target.py
- devlib/trace/ftrace.py
- devlib/trace/systrace.py
- devlib/utils/android.py
- devlib/utils/ssh.py
- doc/connection.rst
- doc/overview.rst
- doc/target.rst
Being able to classify errors coming from transient environment issues (network failure) from actual "fixable" errors that are directly related to the logic of the code is needed for large scale automated testing. It can also be useful to write robust code that will let environment errors bubble up while only catching expected failure of the command started using Target.execute() for example. This PR classifies the TargetError exceptions into 2 categories:
- TargetTransError that reflect environment issues that are not under direct control of the devlib user.
- TargetNonTransError that reflect random issues like network failure.
Ambiguities are lifted assuming the configuration is correct, which allows normal operation in a properly set up automated environment. Incorrect configuration …
> Classify exceptions

- devlib/module/sched.py
- devlib/trace/systrace.py
I used the "Arm Limited" spelling in some headers, but it seems that
didn't get caught by the copyright update script that was used for
9fd690efb303 ("Update copyrights").
This resulted in a duplicated header being inserted, although with the
"ARM Limited" spelling. Remove the previous header and use this one
instead.
> Remove duplicate copyright headers

- devlib/utils/ssh.py
As stated in https://github.com/ARM-software/devlib/issues/308 devlib can leave ssh connections open after they are 
no longer in use, so now register the close method with atexit so the 
connections are no longer left open upon exit.
> ssh: Use atexit to automatically close ssh connections

- devlib/target.py
- tests/test_target.py
Extend Target.read_tree_values() to handle notes that contain line
breaks in their values. Underlying this method, is a call to
grep -r '' /tree/root/
When files under that location contain multiple lines, grep will output
each line prefixed with the path; e.g. a file "test" with the contents
"one\n\ntwo\n" will be output by grep as:
/tree/root/test: one
/tree/root/test:
/tree/root/test: two
Previous implementation of read_tree_values() was assuming one value per
line, and that the paths were unique. Since it wasn't checking for
duplicate paths, it would simply override the earlier entries resulting
with the value of "two" for test.
This change ensure that such multiline values are now handled correctly,
and the entire value is preserved.
To keep compatibility with existing uses of …
> target: read_tree_values: handle multiline values

- devlib/utils/rendering.py
Add missing encoding of string when writing out fps data.
> utils/rendering: Fix Python 3 compatibility

- devlib/module/sched.py
The regexp was a bit too greedy and would match 'cpu1' as the
name of a 'cpu10' node.
> module/sched: Fix sched procfs parsing for >= 10 CPU systems

- devlib/target.py
Commit 511d4781646b ("exceptions: Classify transient exceptions")
introduced a "will_succeed" argument in target.execute(). This argument
is then passed down to conn.execute(). However, since it is not
labelled, this argument happens to overwrite the "strip_colors" argument
of conn.execute because of its position in the list of parameters.
Fix this by labelling the arguments.
Signed-off-by: Quentin Perret <quentin.perret@arm.com>
> target: Ensure colours are stripped from target.execute()

- devlib/target.py
When a module is not supported by the target, remove it from the
"modules" list attribute, so code can check if a module was successfully
loaded by just looking at that list after Target.setup() is done.
> target: Remove failed modules from target.modules

- devlib/module/sched.py
Running some tests on a VM I hit that unexpected scenario where the
required sched_domain file is there but then read_tree_values() fails
because there are no files to read, only directories.
This does a quick check that there's actual data to be read.
> module/sched: Harden probe()

- devlib/utils/misc.py
Document the issue with using memoized with mutable types.
Related to https://github.com/ARM-software/devlib/issues/341
> utils/misc: document memoized limitation

- devlib/utils/misc.py
Use __get_memo_id() for keyword arguments, rather than stringifying
them.  The has somewhat lower chance of producing the same identifier
for two conceptually unequal objects.
Fix for https://github.com/ARM-software/devlib/issues/342
> utils/misc: memoized: fix kwarg IDs

- devlib/target.py
Command 'settings get system user_rotation' does not report current screen orientation value when auto-rotate is enabled or device does not support it (returning null).
Replaced command used by get_rotation to 'dumpsys input'. It should now return current screen orientation value (0-3).
> devlib/target: change get_rotation (Android)

- devlib/host.py
- devlib/instrument/acmecape.py
- devlib/instrument/arm_energy_probe.py
- devlib/instrument/energy_probe.py
- devlib/platform/gem5.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/misc.py
- devlib/utils/rendering.py
- devlib/utils/ssh.py
This PR address some quoting issues in various places where a string containing a command is fed to a shell, directly or indirectly e.g. through `su`.
The third commit "escaping: Use pipes.quote instead of escape_*" unifies escaping in devlib so that the strings provided to the library are used as is, without further interpolation. That could break code relying on referencing environment variable in provided strings, and code that manually escapes strings in order to work around that. It should be noted that any calling code can make use of `os.path.expandvars` to interpolate env var, and that devlib seems to use both single and double quoting in various places, without clear documented consistency.
This PR was tested on SSH connections for a LinuxTarget only, so it would benefit from …
> [RFC] Fix quoting

- devlib/utils/ssh.py
As stated in https://github.com/ARM-software/devlib/issues/346 the default behaviour of Python 3 is to print the stacktrace for the original exception along with the re-raised exception. Since this exposes the password provided to the scp command, only show the redacted exception backtrace.
> utils/ssh: Remove original traceback from exception

- devlib/instrument/__init__.py
Since we can iterate over the active_channel attribute of Instrument
more than once, make sure to cast the return value of filter() to a list
to avoid issues with python 3.
Signed-off-by: Quentin Perret <quentin.perret@arm.com>
> instrument: Fix active_channels for Python 3

- devlib/utils/serial_port.py
Use try/finally clause in the contextmanager to always close the
connection if an exception is raised.
Also remove "del conn" since it only decrements the reference count,
which is done anyway when the generator function returns.
> serial_port: Handle exception in open_serial_connection

- devlib/trace/__init__.py
- doc/overview.rst
This allows using an FtraceCollector object as a context manager, so
tracing will stop even if the devlib application is interrupted, or if
an exception is raised.
> ftrace: Turn FtraceCollector into a context manager

- devlib/module/cgroups.py
On some devices root is required to configure cgroups therefore run the
command as root if available.
> module/cgroups: Execute command as root when launching cmd in cgroup

- devlib/module/cgroups.py
this makes it cope with both, names starting with or without slashes.
currently, if you omit the leading slash, it will just remove the first character of the directory instead, which is annoying.
the trailing slash isn't needed, if i'm wrong could lstrip() instead...
> cgroups.py: strip slashes, don't drop first char

- devlib/utils/android.py
Add support to `ApkInfo` for dynamically extracting:
- Application activities;
- Methods from each class packed in the APK.
Because of the added requirement for using the Android SDK, refactor in an `ApkInfo._run` method for CLI calls.
NB: This PR contains relatively distinct commits and could be broken down into 2 (or 3?) PRs, if necessary...
> ApkInfo: Dynamically extract activities and class methods

- devlib/bin/scripts/shutils.in
- devlib/target.py
target.read_tree_values_flat() uses shutil to list the files and their
content using the find command. It expects the command output to have a
'/path/to/file:value' format, and splits it on the first occurence of
':' in the string, hence creating a ['/path/to/file', 'value'] vector.
However, whenever one of the directories has ':' in its name, this
simple procedure fails to split the string at the right place. For
example, using shutil's read_tree_values on the debugfs folders of
the PM_OPP subsystem will return:
$ ./shutils read_tree_values /sys/kernel/debug/opp/cpu0/opp\:450000000 1
/sys/kernel/debug/opp/cpu0/opp:450000000/clock_latency_ns:0
/sys/kernel/debug/opp/cpu0/opp:450000000/rate_hz:450000000
/sys/kernel/debug/opp/cpu0/opp:450000000/performance_state:0 …
> target: Fix read_tree_values() with ':' in path

- devlib/exception.py
- devlib/target.py
* Make `KernelConfig` a subclass of `collections.abc.Mapping`, so it learns a read-only mapping API. This makes it play well with other mapping-friendly code.
* Introduce a `TypedKernelConfig` class that maps Kconfig types to Python types. Handling of string options is made more friendly (removing enclosing quotes), and integer options become actual Python integers. Tristate is modelled by an `enum.Enum`, with boolean conversion for straight-forward tests.
Since `TypedKernelConfig` is not a drop-in replacement for `KernelConfig`, it cannot replace `target.config` attribute, but could maybe be exposed as `target.typed_config` (or simply live in another codebase than `devlib`).
> Add a typed mapping API to kernel configuration

- devlib/bin/scripts/shutils.in
Hide tar stderr output, so it does not get mixed with the base64 stream
in case the folder we are tarring is empty.
> shutils: Fix read_tree_tgz_b64 on empty folder

- devlib/target.py
Some strings already quoted and therefore result in being quoted twice.
Strip off existing quotes before quoting the value to prevent this.
> target/TypedKernelConfig: Fix converting to string method

- devlib/target.py
Add an 'items' alias for itteritems to avoid confusion when iterating in
different versions of Python.
> target/kernelconfig: Add alias for itteritems

- devlib/bin/scripts/shutils.in
- devlib/module/hwmon.py
- devlib/target.py
- doc/target.rst
Since target.read_tree_values() has been modified to use tar as a way to
fetch the content of files from the target, it is more robust, but also
much slower. Since that level of robustness is in practice required only
for very specific use-cased, re-introduce the old way of doing read_tree
using find and grep.
read_tree_values() gains a new parameter to specify how files should be
read from the target, with or without tar. It defaults to the old way
of doing things.
Signed-off-by: Quentin Perret <quentin.perret@arm.com>
> target: Speed-up read_tree_values()

- devlib/instrument/acmecape.py
pipes.quote() doesn't like integers:
```
>>> from pipes import quote
>>> quote(42)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.5/shlex.py", line 282, in quote
if _find_unsafe(s) is None:
TypeError: expected string or bytes-like object
```
Convert buffer_size to str when quoting it
> acmecape: Fix buffer_size use with pipes.quote()

- devlib/utils/ssh.py
Command line echoing was disabled, but that disabling did not take
effect. Another part of devlib was still expecting command lines to be
echoed. That is fixed by disabling echoing when creating pxssh
connection, and removing the code that expected the line to be echoed.
That PR is somehow linked to https://github.com/ARM-software/devlib/pull/259, since the inconsistency was discovered because of the command line sometimes wraps around.
> ssh: Fix command line echoing

- devlib/target.py
When using Python 2.7 `int`s have a maximum size which can be exceeded
when attempting to convert the hex representation back. Change `HexInt` to
be a `long` instead to avoid this issue.
> target/HexInt: Fix to inherit from long instead of int.

- devlib/target.py
The `long` type is no longer present in Python3 so import it from
`past.builtins` for compatibility.
> target: Fix missing import for Python3

- devlib/host.py
When using sudo with LocalConnection, execute the input command via 'sh
-c' to ensure any shell syntax within the command is handled properly.
Fixes https://github.com/ARM-software/devlib/issues/374
> host: expect shell syntax inside LocalConnection.execute

- devlib/module/sched.py
There are two ways we can load CPU capacity. Up until 4.14, supported
kernels did not have the /sys/devices/system/cpu/cpuX/cpu_capacity file
and the only way to read cpu capacity was by grepping the EM from
procfs sched_domain output. After 4.14, that route still exists but is
complicated due to a change in the format once support for
frequency-power models was merged.
In order to avoid rewriting the procfs EM grepping code, lets switch the
order of algorithms we try to use when loading CPU capacity. All newer
kernels provide the dedicated sysfs node and all kernels which do not
have this node use the old format for the EM in sched_domain output.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
> devlib/sched: Change order of CPU capacity algorithms

- devlib/trace/dmesg.py
Allows collecting dmesg output and parses it for easy filtering.
> trace: Add DmesgCollector

- devlib/trace/perf.py
Context
----------
A `SIGKILL` is, by definition, not allowed to be handled by a process. Therefore, a process receiving this signal isn't able to "clean up" before termination. This is particularly problematic in the case of programs that have "buffered" data (to limit filesystem I/O) and/or that are supposed to output their result when returning.
Typically, `perf` is used with a target command (_e.g._ `sleep` in the `COMMAND_TEMPLATES`). It collects samples (or does something else depending on the command and flags) until that command returns at which point, it writes back its result (`perf.data`, output to `stdout`, ...) before its own termination.
However, if a `SIGKILL` (or other similar signal) is sent to `perf`, this can't happen for the reason detailed above and its results are …
> Soften POSIX signal for termination of perf

- devlib/target.py
On some targets some entries in `/sys/devices/system/cpu` require root
to list otherwise will return a permission error.
> target: Use root if available when determine number of cpus

- devlib/target.py
Apart from busybox, devlib itself makes use of other system provided binaries.
For example, the DmesgCollector module uses the system provided dmesg.
In cases the system provided binary does not support some of the features
required by devlib, we currently just fails with an error.
For the user it is still possible to deploy a custom/updated version of a
required binary via the Target::install API. However, that binary is not
automatically considered by devlib.
Let's ensure that all Target::execute commands use a PATH which gives priority
to devlib installed binaries.
> target: Ensure we use installed binaries

- devlib/__init__.py
Allow using 'import devlib.DmesgCollector', just like
devlib.FtraceCollector.
note: not sure if this kind of import is just there for backward compatibility, or is expected to be used for new code as well.
> devlib: Re-export DmesgCollector in devlib package

- devlib/module/thermal.py
Instead of raising an exception, log an error and carry on.
> module/thermal: Gracefully handle unexpected sysfs names

- setup.py
In the latest versions of panadas and numpy python2.7 support has been
dropped therefore restrict the maximum version of these packages.
> setup.py: Set maximum package version for python2.7 support

- devlib/module/sched.py
The existing behaviour assumes that the cap_states file contains a list
of capacity|cost pairs, and attempts to return the maximum capacity by
selecting the value at the second last index of the list.
This assumption fails on some newer Qualcomm kernels where the
cap_states file contains a list of capacity|frequency|cost triplets.
Consequently, the maximum frequency would be erroneously returned
instead of the maximum capacity.
Fix the problem by dynamically calculating the index of the maximum
capacity by dividing the number of entries in cap_states by the value in
nr_cap_states.
---
For example, on a Snapdragon 855 device:
/proc/sys/kernel/sched_domain/cpu0/domain0/group0/energy/cap_states
54 entries:
CAP     FREQ    COST
--------------------
65	300000	12
87	403200	17
104	480000	21
125 …
> module/sched: Return the correct maximum capacity

- devlib/utils/android.py
Slight rework of `adb_shell` to improve readability and stability but, most importantly, to address #386.
Please note that this requires modern Py3 and should be merged post-WA3.1 (preferred) or could be modified to be Py2.7-compatible.
> Improve adb_shell and move to 'su -c'

- devlib/module/cpuidle.py
As per #407 if the kernel is compiled with the ability to switch cpuidle
governors via sysfs `current_governor_ro` is replaced with
`current_governor` so check if the intial path exists before reading.
> module/cpuidle: Add fallback for reading governor

- devlib/utils/android.py
As per https://github.com/ARM-software/devlib/issues/405 not all versions of su support the `-c` parameter so try to determine which invocation should be used upon connection.
> Enable Fallback for new invocation of `su`

- devlib/trace/systrace.py
In `devlib.trace.SystraceCollector`, `start()` returns after executing
`subprocess.Popen()` for systrace. That doesn't mean that systrace is
running though, the function can return even before systrace has had a
chance to execute anything. Therefore, when you run the command
you want to trace, systrace will miss the first seconds of the
execution.
Run systrace with `-u` to unbuffer its stdin and wait for it to print
"Starting tracing (stop with enter)" before returning.
Fixes #403
> trace/systrace: make start() return when tracing has started

- devlib/target.py
- devlib/utils/misc.py
- doc/target.rst
- setup.py
Allow reverting a write to path by using `Target.write_value` as returning a context manager. This is useful to have more guarantees that the target is left in a clean state after the code has executed, even if some exceptions were raised (including user interruptions with `KeyboardInterrupt`).
This is 100% backward compatible, as `undo=False` by default.
> Exit context manager

- devlib/utils/android.py
The fix in commit 964fde2 caused issues with certain command structures,
for example running in the background. To prevent this run the original
command as a subshell.
> utils/android: Fix echoing of commands.

- devlib/trace/dmesg.py
dmesg output seems to sometimes include an empty line. Ignore them, so we don't
fail to match with the regexes.
> trace: dmesg: Ignore empty lines

- devlib/module/cpufreq.py
Turns out you can't change cpufreq attributes on an offlined
CPU (no big surprise!), so use_governor() will fail if a whole
frequency domain has been hotplugged out.
Change the default behaviour to only target online CPUs.
> module/cpufreq: Make use_governor() affect only online CPUs

- devlib/trace/dmesg.py
Allow building a list of KernelLogEntry from a full dmesg output, in addition to
building just one entry using KernelLogEntry.from_str() .
> trace: dmesg: Add KernelLogEntry.from_dmesg_output() classmethod

- devlib/target.py
- devlib/utils/android.py
- devlib/utils/ssh.py
- doc/connection.rst
As per https://github.com/ARM-software/devlib/issues/406 currently in order to enable adbd as root, a connection to the target already needs to exist however there are use case that we want to perform initialising as root as well.
- Add a utility function to restarted adbd in rooted and unrooted mode.
- Add the `adb_as_root` connection parameter to `AdbConnection`.
Note: This will restart adbd as root before attempting to connect to the target and will also restart adbd unrooted upon the last disconnection from the target.
> Allow for restarting adb as root upon connection. 

- devlib/target.py
Remove the target `adb_name` from the call as this method is an instance
method.
Fixes: https://github.com/ARM-software/devlib/issues/428
> AndroidTarget: Fix additional paramter to `adb_root`

- devlib/instrument/acmecape.py
- devlib/instrument/arm_energy_probe.py
- devlib/instrument/daq.py
- devlib/instrument/energy_probe.py
- devlib/instrument/frames.py
- doc/instrumentation.rst
Implement the `teardown` method in instruments that utilise tempfiles
which were previously left behind.
> instruments: Add teardown method to clean up tempfiles

- devlib/module/thermal.py
Listing thermal zones directories in sysfs fails when running as non-root.
Signed-off-by: Douglas RAILLARD <douglas.raillard@arm.com>
> module/thermal: List directories with as_root=True

- devlib/target.py
On some unrooted devices the checking of root status can cause a
`TargetTransientError` therefore update `except` statement to accommodate
these.
> Target: Allow `TargetTransientError`s when checking for root

- devlib/trace/ftrace.py
Recent `trace-cmd` supports `-C <clock>` option, but since it's not present on older versions (notably the one used in LISA), use the sysfs file instead.
> Allow changing ftrace clock and ftrace saved cmdlines buffer nr of entries

- devlib/trace/ftrace.py
"function_graph" tracer allows getting funcgraph_entry/funcgraph_exit events for
listed functions. This allows getting precise information on when a given
function was called, and how long its execution took (to build a time-based
heatmap for example).
This can be enabled using:
FtraceCollector(target, functions=['foo', 'bar'], tracer='function_graph')
If needed, children functions can also be traced with
trace_children_functions=True .
Signed-off-by: Douglas RAILLARD <douglas.raillard@arm.com>
> ftrace: Enable alternative tracers

- devlib/module/cgroups.py
The docstring of `Controller.move_all_tasks_to()` says that the function moves all the tasks to the `dest` cgroup.  However, it iterates over `self._cgroups`, which is a dictionary that is lazily populated when you call `Controller.cgroup()`.  For example, this doesn't work:
``` python
cpuset_cg = target.cgroups.controller("cpuset")
cpuset_cg.move_all_tasks_to("top-app")
```
Because you haven't populated `self._cgroups` yet.  You need to manually populate the dictionary with something like:
``` python
for group in cpuset_cg.list_all():                               
cpuset_cg.cgroup(group)
```
before you can use `move_all_tasks_to()`.  Iterate through `self.list_all()` instead of `self._cgroups` to really move all tasks to to the destination directory.  
`Controller.move_tasks()` has a …
> module/cgroups: Really move all tasks in Controller.move_all_tasks_to()

- devlib/exception.py
Unpickling of BaseException is done by feeding self.args to the exception type.
This self.args attribute is initialized in two places: in
BaseException.__new__ (before __init__ is called) and in BaseException.__init__
as well.
The following code ends up with self.args == ('hello',), instead of (1, 2):
class MyExcep(BaseException):
def __init__(self, foo, bar):
print('before super().__init__()', self.args)
super().__init__('hello')
print('after super().__init__()', self.args)
MyExcep(1, 2)
When unplickling such instance, ('hello',) will be fed to MyExcep.__init__(),
which will fail with a TypeError since it requires 2 positional arguments.
In order to fix that, super().__init__() needs to be handwritten instead of
getting the one from BaseException:
class MyBase(BaseException):
def …
> exception: Fix DevlibError unpickling

- devlib/trace/ftrace.py
The content of /proc/kallsyms depends on the value of
/proc/sys/kernel/kptr_restrict:
* If 0, restriction is lifted and kallsyms contains real addresses
* If 1, kallsyms will contain null pointers
Since trace-cmd records the content of kallsyms into the trace.dat and uses that
to pretty-print function names (function tracer/grapher), ensure that its
content is available.
Signed-off-by: Douglas RAILLARD <douglas.raillard@arm.com>
> ftrace: Ensure /proc/kallsyms contains symbol addresses

- devlib/target.py
devlib is used by LISA ( https://github.com/ARM-software/lisa ) for Linux kernel scheduler 
testing. This PR will allow introspection of NUMA typologies.
This PR will allow testing of task placement and migration with respect to 
NUMA topology.
> Add NUMA nodes

- devlib/platform/__init__.py
- devlib/target.py
Move the resolution of the model name from targets into Platform's
_set_model_from_target() (which was already attempting to do that via
dmidecode method).
> target: get model form platform

- devlib/module/__init__.py
- devlib/module/android.py
- devlib/module/vexpress.py
- doc/modules.rst
Adds a `connect` parameter to the flash method to specifiy whether
devlib should attempt to connect to the target after flashing has
completed.
> modules/flash: Add a `connect` parameter to the flash method

- devlib/host.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/ssh.py
- doc/target.rst
As per https://github.com/ARM-software/devlib/issues/410, `AndroidTarget` should be independent to the underlying connection, therefore move ADB specific methods into the `AdbConnection`.
> [Breaking Change] ADB Refactor

- devlib/__init__.py
- devlib/collector/__init__.py
- devlib/collector/dmesg.py
- devlib/collector/ftrace.py
- devlib/collector/logcat.py
- devlib/collector/perf.py
- devlib/collector/screencapture.py
- devlib/collector/serial_trace.py
- devlib/collector/systrace.py
- doc/collectors.rst
- doc/index.rst
- doc/instrumentation.rst
- doc/overview.rst
- doc/target.rst
Refactor the `TraceCollector` as per https://github.com/ARM-software/devlib/issues/383.
> [Breaking Change] Initial implementation of Collector Refactor

- devlib/collector/ftrace.py
Issue: when using an FtraceCollector object with a nop tracer followed by a function_graph tracer, the second one will not work.
This patch makes sure the state is set on reset and left in a proper state on stop.
> devlib/trace/ftrace.py: Fix reset and stop states

- devlib/host.py
Add a host attribute (hard-coded to "localhost") to LocalConnection to
make it easier to seamlessly swap it out with ssh connection.
> host: add host attribute to LocalConnection

- devlib/module/cpufreq.py
Ensure the order of frequencies is deterministic to have consistent output when
printing it or when using it to carry out some actions.
Having the fix in devlib sounded better than carrying that in LISA, since other code base might rely on that:
https://github.com/ARM-software/lisa/pull/1262
> module/cpufreq: Sort list of frequencies

- devlib/target.py
logcat has a modifier for its output format.  Add a `logcat_format` parameter to `dump_logcat()` so that we can pass it on to logcat.
> devlib/AndroidTarget: Allow passing format options to dump_logcat()

- devlib/target.py
Make sure the target.modules list stays up to date when a new module is
installed, since behaviors like devlib_cpu_frequency event injection rely on
content of target.modules.
> target: Update Target.modules from Target.install_modules()

- devlib/target.py
Some SoC vendors add several sha's to the kernel version string. This is
problematic for the KernelVersion class, which might identify the wrong one.
Fixing this issue by matching the following "git describe" pattern:
<version>.<major>.<minor>-<rc>-<commits>-g<sha1>
Where commits is the number of commits on top of the tag, which is now a
member of the class.
Prior to this patch:
>> KernelVersion("4.14.111-00001-gd913f26_audio-00003-g3ab4335").sha1
3ab4335
>>> KernelVersion("4.14.111_audio-00003-g3ab4335").sha1
3ab4335
With the modified regex:
>> KernelVersion("4.14.111-00001-gd913f26_audio-00003-g3ab4335").sha1
d913f26
>>> KernelVersion("4.14.111_audio-00003-g3ab4335").sha1
None
> target: a valid sha1 must be concatenated with the kernel version

- devlib/connection.py
- devlib/host.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/misc.py
- devlib/utils/ssh.py
- setup.py
Here is an crude port of SshConnection to paramiko, so pxssh can rest in peace.
Quote from a pexpect maintainer in 2014 on https://github.com/DFE/MONK/issues/108:
> As a maintainer of pexpect, I highly recommend using paramiko instead of pexpect for ssh :) pexpect's ssh support is from long ago where no native-ssh option existed, it only remains for compatibility.
With paramiko, remote programs will not detect you as a terminal and will not likely write terminal sequences.
Note: it might be a better idea to just introduce a new class rather than ruthlessly modifying SshConnection, since TelnetConnection relies on pexpect and the recent addition of `options` parameter will not allow easily moving away from an actual ssh/scp command. (paramiko seems to have an OpenSSH config emulation, …
> ssh: Use paramiko instead of pxssh

- doc/connection.rst
- doc/derived_measurements.rst
- doc/index.rst
- doc/instrumentation.rst
- doc/modules.rst
- doc/overview.rst
- doc/platform.rst
- doc/target.rst
To address https://github.com/ARM-software/devlib/issues/379 add the `module` directive to allow the documentation to be referenced from other modules as well as enabling links to the source code directly from the documentation.
Also adds reference to the `LinuxTarget` and `LocalLinuxTarget` classes.
> Documentation Update

- devlib/utils/ssh.py
By default parmaiko attempts to search for SSH keys even when connecting
with a password. Ensure this is disabled to prevent issues where
non-valid keys are found on the host when connecting using password
authentication.
> utils/ssh: Only try SSH keys if no password is supplied.

- devlib/utils/android.py
- devlib/utils/misc.py
`check_output(combined_output=True)` does not guarantee that stdout will come before stderr, but the ordering is needed in case `check_exit_code` is `True`, as we are expecting the exit code at the end of stdout. Furthermore, the exceptions can't report what is stdout and what is stderr as they are combined.
Partially revert 77a6de9 ("utils/android: include stderr in adb_shell output") and parse output and err independently. Return them combined from `adb_shell()` to keep the functionality that 77a6de9 was
implementing.
> Combined output fix

- devlib/utils/misc.py
If an error occurs while executing a command the `output` and `error`
variables may not get initialised, only attempted to decode their
contents if this is not the case.
> utils/check_output: Only attempt to decode output if present.

- devlib/utils/misc.py
Ensure that the `output` and `error` variables are always initialised
regardless of whether an error occurs during execution.
> utils/check_output: Ensure `output` and `error` are always initialised.

- README.rst
Update to provide links to `paramiko` installation documentation as some stripped down systems can require additional installation dependencies.
> README: Update to include installation notes for `paramiko`

- devlib/utils/android.py
The documentation for the collectors uses LogcatCollector() as an example, but I don't think it has ever worked with python3. This PR fixes the collector so that it works as the documentation expects it to.
> Logcat collector fix

- devlib/utils/android.py
- doc/connection.rst
Allow for configuring the number of connection attempts that will be
made to the device before failing to connect. This allows for waiting longer
periods of time for the device to come online.
> utils/android: Expose `connection_attempts` argument to `AdbConnection`

- devlib/collector/perf.py
Pipe the list of perf events via cat to ensure that a pager is not
used to display the output as this can cause some systems to hang
waiting for user input.
> collector/perf: Disable pager for perf event list.

- devlib/collector/logcat.py
- devlib/utils/android.py
logcat -v lets you specify the format for the logcat output.  Add a
parameter to the LogcatCollector to allow us to pass that information
down to the logcat invocation.
> LogcatCollector: Learn to pass format to logcat

- devlib/utils/ssh.py
No longer recursively attempt to push a file to the target. If the
second attempt goes wrong we assume there is something else wrong and
therefore let the error propagate.
Also log the original error in case it is not the error we were
expecting.
> utils/ssh: Do not attempt to push files recursivley and add logging

- devlib/utils/android.py
Do not assume that a path is provided upon creating of an ApkInfo
instance and only attempt to extract information if present.
> utils/android: Allow instantiating an ApkInfo object without a path.

- devlib/target.py
- doc/target.rst
Newer devices can have a "DOZE" or always on screen state.
Enable the screen state to handle these cases and report these
states as `ON`.
> devlib/AndroidTarget: Update screen state methods to handle doze

- devlib/module/cpuidle.py
Replace stateful loop with a nested comprehension that makes obvious:
* that self._states is a dict(cpu, [CpuidleState])
* the sysfs folder being used and the constraint applied to make use
of each level (i.e. which subfolder is used)
* that the states are sorted by index
As a side effect:
* Gracefully handle non-contiguous idle state names like "state0,
state2" without a state1 (not sure if that can happen)
* Remove some antipatterns while iterating over a dict and counting
iterations.
> module/cpuidle: Simplify Cpuidle.__init__

- devlib/utils/android.py
- doc/overview.rst
Allows falling back to discovering of the currently required android tools from PATH instead of an Android SDK installation. 
Enable the discovery of `aapt2` and default to this if a suitable binary is found:
- This is required due to the fact that `appt` is now depreciated and cannot handle some apks which have valid characters in their description.
- Unfortunately `aapt2` versioning does not seem very mature yet and does not have a nice way of determining whether a particular version supports the subcommands that devlib requires. For example the `version` output from a known working version is `Android Asset Packaging Tool (aapt) 2.19-SOONG BUILD NUMBER PLACEHOLDER`. 
- Therefore to detect if a suitable version is present, try to execute a sub command and look for an expected error …
> [RFC] Update android tools discovery

- devlib/module/vexpress.py
This method is also called when booting linux so remove specific
reference to Android.
> module/vexpress: Remove reference to android.

- devlib/target.py
Some targets can thrown stable errors in addition to
transient errors when executing the `reboot` command.
We expect this command to not always complete cleanly
so ignore all target errors.
> target/reset: Ignore all `TargetError`s when rebooting

- devlib/utils/android.py
Fix syntax error in dump command when using the aapt binary.
> utils/android: Fix xmltree dump for aapt

- devlib/utils/android.py
Create a new temporary directory to use when extracting apk methods,
as when running multiple processes in parallel the extracted files could
be overwritten by each other.
> utils/android: Use separate tmp dirs when extracting apk methods

- devlib/target.py
By passing 'threads=True' to target.ps(), a list of PsThreadEntrys will be
returned for all threads in the target, not just processes. These entries
include an extra value 'tid': the thread ID of this thread. The 'pid' value
represents the pid of the process the thread belongs to.
> target: support threads in ps

- devlib/target.py
- doc/target.rst
Adds the ability to set the android global setting
``stay_on_while_plugged_in``.
This setting has 4 main modes:
- 0: never stay on
- 1: stay on when plugged in to AC charger
- 2: stay on when plugged in to USB charger
- 4: stay on when wirelessly charged
These values can be OR-ed together to produce combinations.
> devlib/target: Enable screen stay-on mode:

- devlib/utils/android.py
Not all apks list their class methods so add handling of this
situation.
> utils/apkinfo: Fix handing when no methods defined

- devlib/connection.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/misc.py
- devlib/utils/ssh.py
- doc/connection.rst
- doc/target.rst
- setup.py
Implements file transfer polling for ADB and SCP,SFTP based transfers.
> connections,targets: Add file transfer polling

- devlib/host.py
- devlib/utils/ssh.py
On a target where sudo is required, target.file_exists() erroneously
returns True despite the execute() output being:
'[sudo] password for valsch01: 0\n'
The sudo prompt is being written to stderr (as per sudo -S), but this is
still merged into the final execute() output. Get rid of the prompt to
prevent it from interfering with any command output processor.
> utils/ssh: Remove sudo prompt from output

- devlib/utils/android.py
Ensure the adb_server is specific when monitoring the logcat.
> utils/logcatmonitor: Ensure adb_server is specified

- devlib/utils/android.py
- devlib/utils/gem5.py
- devlib/utils/misc.py
- devlib/utils/ssh.py
Fix invalid escape sequence, mostly in regex that were not r-strings.
> devlib.utils: Fix escape sequences

- devlib/utils/android.py
Some apks do not contain the file that we use to determine app methods
so return an empty list in this case.
> utils/apk_info: Handle apks that do not contain classes.dex

- devlib/utils/android.py
- setup.py
As detailed in https://github.com/ARM-software/workload-automation/issues/1151 dexdump in the latest releases (v30.0.1, v30.0.2 and v30.0.3) of android build tools can produce invalid xml due to not escaping special values contained within some APK files.
The built in `xml` module does not seem capable of handling invalid xml data therefore the proposed solution is to switch to the `lxml` module instead which is better equipped to recover data from invalid input.
-----
Additionally fix an issue with `aapt` discovery when presented with an unexpected directory structure.
> [RFC] Fix broken XML parsing due to android tools update

- devlib/target.py
If WA is connected to a phone via a slow connection, dump_logcat() may
timeout when dumping logcat after the job has finished:
2021-01-11 09:38:16,277 DEBUG       android:         adb -s X.Y.Z.X:5555 logcat -d -v threadtime > wa_output/wk1-wkld-1/logcat.log
2021-01-11 09:38:46,317 DEBUG        signal:         Sending error-logged from <ErrorSignalHandler (DEBUG)>
2021-01-11 09:38:46,318 DEBUG        signal:         Disconnecting <bound method Executor._error_signalled_callback of executor> from error-logged(<class 'louie.sender.Any'>)
2021-01-11 09:38:46,317 ERROR        signal:         Timed out: adb -s X.Y.Z.X:5555 logcat -d -v threadtime > wa_output/wk1-wkld-1/logcat.log
2021-01-11 09:38:46,317 ERROR        signal:         OUTPUT:
2021-01-11 09:38:46,317 ERROR        signal:
2021-01-11 …
> target: increase dump_logcat timeout

- devlib/utils/version.py
On systems that do not have git installed devlib will currently fail
to install with a FileNotFound Exception. If git is not present then
we will not have a commit hash so just ignore this error.
> utils/version: Prevent installation failure on systems without git

- devlib/collector/perf.py
If you want to collect events by event id (eg. in simpleperf, "rNNN" with NNN a number), you must run it as root.  Otherwise, simpleperf fails with a SIGABRT:
simpleperf F environment.cpp:856] Check failed: tmp_file->fd != -1 (tmp_file->fd=-1, -1=-1)
Aborted
Run simpleperf as root by default if the target is rooted to avoid this.
> collector/perf: Run perf as root if the target is rooted

- devlib/host.py
- devlib/utils/ssh.py
Add -k to sudo invocation to avoid using cached credentials.
If cached credentials is used, sudo will not write a prompt again,
leading to the stderr fixup code to remove a char from stderr output.
> host and ssh: Fix sudo invocation

- devlib/collector/dmesg.py
Fail early if the target is not rooted, as root is required by
DmesgCollector.start() anyway.
> collector/dmesg: DmesgCollector: Avoid not rooted targets

- devlib/module/hotplug.py
The Linux HP path is composed of a series of states the CPU has to execute
to perform a complete hotplug or hotunplug. Devlib now exposes this
information. get_state() gives the current state of a CPU. get_states()
gives the list of all the states that composes the HP path.
The Linux HP 'fail' interface allows to simulate a failure during the
hotplug path. It helps to test the rollback mechanism. Devlib exposes this
interface with the method fail().
> module/hotplug: Extend hotplug support with 'fail' and 'states' interfaces

- doc/target.rst
Add caveat for the hostid on PowerPC64 devices due to the library
used when linking the included binary.
> docs: Add note to hostid about PowerPc64 devices

- devlib/module/hotplug.py
Check that all CPUs are effectively online after a call to
target.hotplug.online_all(), as hotplug issues are common and failure to
bring back up a CPU can be quite problematic.
> hotplug: Verify hotplug.online_all()

- devlib/utils/ssh.py
Ensure that the stdin for paramiko is opened for writing instead of reading and fix incorrect stream for reading.
> Paramiko Fixes

- devlib/target.py
- devlib/utils/misc.py
Using a threading.Lock leads to a deadlock in some circumstances.
> utils/misc: Use RLock for check_output_lock

- devlib/connection.py
Some target implementations of kill do not support killing
process groups so use the busybox implementation for greater
portability.
> connection: Use busybox implementation of `kill`

- devlib/target.py
For greater portability ensure that we use the busybox
implementation for all kill commands.
> target: Use busybox implementation of `kill`

- devlib/host.py
Fix typo in LocalConnection._copy_path(): src => source
> host: Fix typo s/src/source

- devlib/utils/ssh.py
Move methods related to the scp command into TelnetConnection, since
SshConnection do not use it at all anymore (it has been replaced by the
"scp" python package, piggy backing on paramiko).
> ssh: Move legacy scp out of SshConnectionBase

- devlib/target.py
Convert paths to str() so that passing a pathlib.Path works.
> target: Make Target.push/pull work with pathlib

- devlib/host.py
- devlib/utils/android.py
The Popen object created for background command currently has no stdin
pipe, preventing the user from writing to it (it will be None instead of
being a file-like object).
Fix that by passing stdin=subprocess.PIPE to Popen constructor.
> host: Fix PopenBackgroundCommand stdin

- devlib/connection.py
- devlib/utils/ssh.py
Ease blocking interaction with a BackgroundCommand object, in the style of Popen.communicate()
Tested on paramiko and local target, but not android.
> Add BackgroundCommand.communicate()

- devlib/target.py
The main path is reading /proc/config.gz. If it does not exists, the
following paths are tested:
'/boot/config', '/boot/config-$(uname -r)'
Since the 2nd path contains a command to be executed, remove quoting of
the path when using "cat".
> target: Fix fallback path for kernel config loading

- devlib/target.py
`__getstate__` is also used by the copy module, but allows pickling the
class as well. This is useful when using the multiprocessing API, which
requires pickling the Target object to send it to the new process.
Background: I'm making use of the Linux's user and mount namespace in order to compile kernel modules (so I can mount overlayfs and use chroot into Alpine without requiring sudo), which require using a separate process. The process unfortunately needs to interact with the target, which means the Target object needs to be pickled and sent to it on a pipe.
> target: Replace Target.__copy__ by __getstate__

- devlib/module/sched.py
Use target.list_directory(as_root=target.is_rooted) instead of doing it
as a normal user for paths in /sys/kernel/debug. Since this
list_directory() call can be used with multiple path, we do not force
as_root=True but we increase the chance of it working.
> modules/sched: Use correct permissions to read debugfs

- devlib/utils/android.py
Some Android devices do not have 'su'. But if they are already
rooted, there's no reason to fail. Circumvent this scenario by never
using 'su' for device already rooted.
> utils.android: force as_root=False when connected_as_root

- devlib/bin/scripts/shutils.in
- devlib/collector/ftrace.py
Android 12 mounts tracefs in a different location, so auto-detect it rather than relying on hard-coded values.
> Fix tracefs

- devlib/target.py
Currently, it is not possible to push/pull files with a relative path. This
is due to the basename resolution. Fix this beahviour.
> target: Allow relative path for for push/pull

- devlib/target.py
Avoid pickling the "clear_logcat_lock". Instead, discard the attribute
and re-initialize it anew.
This issue currently prevents compiling the LISA kernel module from within LISA as we need to send-over the Target instance to a separate process (using pickle, in order to run the process in a separate user and mount namespace)
> target: Fix AndroidTarget pickling

- devlib/module/cgroups.py
Currently the cgroups module will pull all available controllers from
/proc/cgroups and then try to mount them, including the disabled ones.
This will result in the entire mount failing.
Lines in /proc/cgroups ending in 0 correspond to disabled controllers.
Filtering those out solves the issue.
> module/cgroups: Skip disabled cgroup controllers

- devlib/target.py
Fix __setstate__ to call super().__setstate__ in order to handle the
generic part of the deserialization.
> devlib.target: Fix AndroidTarget unpickle

- devlib/module/android.py
- devlib/module/vexpress.py
- devlib/target.py
- devlib/utils/misc.py
Prevent potential directory path traversal attacks (see https://www.trellix.com/en-us/about/newsroom/stories/research/tarfile-exploiting-the-world.html)
This is an alternative to the automatically generated https://github.com/ARM-software/devlib/pull/607 without code duplication.
> Mitigate CVE-2007-4995

- devlib/collector/ftrace.py
- devlib/host.py
- devlib/instrument/acmecape.py
- devlib/instrument/arm_energy_probe.py
- devlib/instrument/energy_probe.py
- devlib/platform/gem5.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/misc.py
- devlib/utils/rendering.py
- devlib/utils/ssh.py
pipes module is deprecated since 3.11, and quote() has been available in
shlex since 3.3.
Addresses https://github.com/ARM-software/devlib/issues/609
> Import quote() form shlex rather than pipes

- devlib/collector/dmesg.py
- devlib/collector/ftrace.py
- devlib/derived/energy.py
- devlib/derived/fps.py
- devlib/instrument/__init__.py
- devlib/instrument/acmecape.py
- devlib/instrument/arm_energy_probe.py
- devlib/instrument/energy_probe.py
- devlib/instrument/frames.py
- devlib/instrument/gem5power.py
- devlib/instrument/hwmon.py
- devlib/instrument/netstats/__init__.py
- devlib/platform/arm.py
- devlib/utils/misc.py
- devlib/utils/ssh.py
- setup.py
Remove the "future" dependency as devlib does not support Python 2 anymore.
Also remove the "from __future__ import division" as this is the default in Python 3.
Fixes #612
> devlib: Remove "future"

- devlib/module/cgroups2.py
Handles both V1 and V2 CGroups transparently with an API matching
CGroup V2 semantics.
Also handles the CGroup delegation API provided by systemd.
> module/cgroups2: Add new CGroups management module

- devlib/collector/ftrace.py
Use a buffer named "devlib" instead of using the top-level default buffer. That will improve interop with other tools trying to collect a trace at the same time as devlib.
> ftrace: Use named ftrace buffer

- devlib/collector/ftrace.py
trace-cmd extract needs -B devlib to be passed, otherwise an empty buffer will be extracted.
> ftrace: Fix use of named buffer

- devlib/collector/ftrace.py
FtraceCollector.available_events is not memoized anymore as the set of events supported by the target can change dynamically (e.g. loading a kernel module).
This means that calling self.available_events is somewhat expensive, so avoid doing it in a loop. Instead, save the events in a variable and reuse it in the function to save a substantial amount of time.
> ftrace: Avoid repeated available events query

- devlib/utils/android.py
Ensure adb_root() always raises AdbRootError so that the caller can catch it reliably. This is especially important since adb_root() failing is ignored and simply triggers a fallback on using `su`. Android production builds refuse adb root nowadays, so it's important that adb root failures are handled well.
> utils/android: Fix adb_root() exceptions

- devlib/connection.py
- devlib/host.py
- devlib/utils/android.py
- devlib/utils/ssh.py
Ensure all background commands are terminated before we close the connection.
This PR adds tracking of all outstanding BackgroundCommand inside `ConnectionBase._current_bg_cmds`. This attribute is changed from WeakSet() to set(), and the BackgroundCommand themselves deregister themselves when they terminate. This allows properly canceling _all_ outstanding_ bg command when the connection is closed.
BackgroundCommand.__init__ polls current bg cmds of its connection to reap any terminated commands, so that APIs that leak objects like the change introduced by this PR:
https://github.com/ARM-software/devlib/pull/624
or any other non-careful user does not result in endless leak of associated resources.
> connection: Terminate background commands on close()

- devlib/connection.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/ssh.py
Cleanup and simplify transfer manager infrastructure to make it more reliable.
WARNING: Not tested on SSH connection yet.
Tested on android along https://github.com/ARM-software/devlib/pull/618
> Cleanup transfer manager

- devlib/connection.py
Fix a number of issues discovered during testing of https://github.com/ARM-software/devlib/pull/618/.
- Update kill command syntax to match the currently support busybox implementation.
- Ensure the correct signal is to send to a command.
- Prevent commands from being killed multiple times.
> Fix bg cmds

- devlib/target.py
Some apps, such as Unity-based applications, can store some files in their 'persistent data path' which is usually under '/storage/emulated/0/Android/data'. Add a handle to easily access the path within AndroidTarget in the same way as package_data_directory currently is accessible.
> target: Add persistent_data_path to AndroidTarget

- devlib/utils/rendering.py
Change the SurfaceFlingerFrameCollector to match activities by prefix instead of looking for an exact match. This will allow to account for activities with variable suffixes.
Raise an error if more than one activity matches the provided view.
Suggested-by: Andriani Mappoura <andriani.mappoura@arm.com>
> utils.rendering: Fix activity matching

- devlib/collector/dmesg.py
Only run the minimal amount of commands, as executing a command can be costly.
In the sequence reset() -> start(), we only need to get the output of dmesg upon start() to know what part of the log will be ignored (everything before the call to start()). There is no need to perform that upon reset() since the sequence:
reset() -> start() -> stop() -> start() -> stop()
\______1________/    \______2________/
is anyway equivalent to:
reset() -> start() -> stop()
\______2________/
So reset() can essentially be a no-op and the actual reset logic lives in start().
> collector/dmesg: Avoid unnecessary dmesg command

- devlib/target.py
Installing busybox sometimes fails with:
cp: /data/local/tmp/bin/busybox: Text file busy
Fix that by using the -f option, which will remove the destination file first and retry the copy in case of failure.
> target: Avoid intermittent error when installing binary

- devlib/collector/ftrace.py
Since we now set the top buffer size to be the same as the devlib buffer size, this effectively halves the maximum available buffer size that can be set while using devlib. Whatever size is passed as `buffer_size` will be allocated twice, even if the top buffer is hardly used at all.
This commit separates them into `buffer_size` and `top_buffer_size`. If the latter is not passed, the behaviour will not change compared to now.
Fixes: e0c53d09990b5501e493d048a5dce067d8990281
> ftrace: Separate top_buffer_size from buffer_size

- devlib/utils/android.py
Ensures that adb commands are executed with english locale since we sometimes match on the output.
Needs testing but should fix https://github.com/ARM-software/devlib/issues/599
> utils/android: Use LC_ALL for adb commands

- devlib/__init__.py
- devlib/collector/perfetto.py
- devlib/target.py
Add a Collector for accessing Google's Perfetto tracing infrastructure. The Collector takes a path to an on-device config file, starts tracing in the background using the perfetto binary and then stops by killing the tracing process.
Signed-off-by: Kajetan Puchalski <kajetan.puchalski@arm.com>
> devlib.collector: Add PerfettoCollector

- devlib/utils/ssh.py
Using SSHConnection(use_scp=True) lead to an exception:
UnboundLocalError: local variable 'handle' referenced before assignment
This is cause by some (false) cyclic dependency between initialization of SSHTransferHandle and creation of the SCPClient. We can fix that by adding a level of indirection to tie together both objects.
> utils/ssh: Fix SSHTransferHandle when using SCP

- devlib/collector/ftrace.py
The sysfs documentation mentions that the value written to buffer_size_kb ftrace field may be rounded up.
So skip the verify loop on this field.
The case we are worried about, a requested buffer
size that the target cannot fulfill is caught anyway, as the sysfs write returns with an error that is caught.
> ftrace: Do not read-verify buffer_size_kb value

- devlib/module/thermal.py
The thermal module currently only reads thermal zone ids and allow temperature reading. The mandatory thermal zone 'type' describes what the zone is and is therefore quite useful information. This commit also adds support for reading the current thermal zone policy and available policies.pp
> devlib: Add ThermalZone type and policy support to thermal module

- devlib/target.py
Android GKI kernels have versions such as:
5.15.110-android14-11-ga6d7915820a0-ab10726252
Update the parsing regex to include:
* gki_abi: 10726252 in this example
* android_version: 14 in this example
This also allows parsing the git sha1 correctly, which otherwise is broken on a version like that.
Fixes https://github.com/ARM-software/devlib/issues/654
> target: Update kernel version parsing for Android GKI kernels

- devlib/utils/android.py
dex file search for the package name is modified. In the apk, package name stated twice and the second one includes the tests information. Tested with other benchmarks (geekbench,pcmark,jankbench in Android 12) as well.
> UIBenchJankTests: modification to support Android 12/14 versions

- devlib/target.py
Don't throw an error if attempting to grant a permission that is not manageable.  
Reported in https://github.com/ARM-software/workload-automation/issues/1234 & https://github.com/ARM-software/workload-automation/issues/1212
> AndroidTarget: Skip ungrantable Android permission

- devlib/collector/ftrace.py
- devlib/instrument/acmecape.py
- devlib/instrument/energy_probe.py
- devlib/instrument/monsoon.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/csvutil.py
- devlib/utils/misc.py
- devlib/utils/rendering.py
- devlib/utils/ssh.py
- devlib/utils/types.py
- devlib/utils/version.py
- setup.py
Python 3.12 removed the "imp" module, so replace its use in devlib.
closes https://github.com/ARM-software/devlib/issues/644
> setup.py: Remove use of "imp" module

- devlib/target.py
Changed target variable to self because it is not defined in the file.
> target: Fix typo

- devlib/utils/android.py
I noticed the following errors during invocation of uibench/uibenchjanktests:
job:     Initializing job wk1 (uibench) [1]
signal:         Sending before-workload-initialized from wk1 (uibench) [1]
apk:         Resolving package on host system
resolver:         Resolving <<Workload uibench>'s apk 14>
resolver:         Trying user.get
signal:         Sending error-logged from <ErrorSignalHandler (DEBUG)>
signal:         Disconnecting <bound method Executor._error_signalled_callback of executor> from error-logged(<class 'louie.sender.Any'>)
signal:           File "/repos/lisa/external/workload-automation/wa/framework/signal.py", line 324, in wrap
signal:             yield
signal:           File "/repos/lisa/external/workload-automation/wa/framework/job.py", line 97, in initialize
signal: …
> [Android] Fix use-before-initialization during initialization of ApkInfo

- devlib/utils/android.py
- devlib/utils/misc.py
- setup.py
- tests/target_configs.yaml
- tests/test_target.py
**Commits:**
1. [utils/android: Add debug log about connection settings](https://github.com/ARM-software/devlib/pull/670/commits/2169e61)
1. [utils/misc: Move load_struct_from_yaml() from WA to devlib](https://github.com/ARM-software/devlib/pull/670/commits/fb8887f)
1. [tests/test_target: Read target connection settings from a YAML file](https://github.com/ARM-software/devlib/pull/670/commits/6217c77)
---
> Read target connection settings from a YAML file

- devlib/collector/perf.py
The validation call can take a long for targets where PLL:s have been clocked down, such as FPGAs.
> Add option not to validate PMU counters.

- devlib/utils/misc.py
For example if `[3,1,2]` was provided, it would result in `3,1-2`, but after writing this to a sysfs file, it would read back as `1-3`
> Fixed issue where non-consecutive list resulted in incorrect ranges

- devlib/utils/ssh.py
SshConnection registers an atexit handler so the connection is closed upon exiting the process if it has not been done before. However, the handler keeps a reference on the connection, which means it _will_ stay alive. If lots of short-lived connections are created (which can happen when using e.g. ThreadPoolExecutor), they will simply stay around and leak.
Fix that by using a weak reference (WeakMethod) to register in the atexit handler, with a callback to unregister it when the object is deallocated.
Fixes https://github.com/ARM-software/devlib/issues/676
> utils/ssh: Fix atexit.register() SshConnection leak

- devlib/target.py
- doc/tools.rst
- tests/target_configs.yaml.example
- tests/test_target.py
- tools/docker/Dockerfile
- tools/docker/run_tests.sh
- tools/docker/target_configs.yaml
**Commits:**
* c659c2b - test_target.py: Allow specifying connection timeout for Android targets
* 3e708bb - tools/docker: Add Docker image support for devlib
> tools/docker: Add Docker image support for devlib

- devlib/target.py
- tests/target_configs.yaml.example
- tests/test_target.py
**Commits:**
* 24a084e - target: Address pylint issues in ChromeOsTarget class
* 1bd22c4 - target: tests: Add support for testing ChromeOS targets
> Add support for testing ChromeOS targets

- devlib/module/__init__.py
- devlib/target.py
Cleanup module code to improve robustness, modularity and enable lazy loading of modules.
The main features are:
* More checks (e.g. it is now impossible to add multiple modules of the same kind)
* Predictable Target.modules content: it used to be a mix of str and dict, now it's str only
* Modules don't have to be declared in `Target(modules=...)` anymore to be used. They can simply be accessed and that will load them lazily. Passing `Target(modules=[{mod: None}])` will prevent loading of the module in all circumstances, including lazily.
For now, modules passed to `Target(modules=...)` will be eagerly loaded, but that could be changed quite easily to enable full lazy loading if we wanted.
On top of that, the list of default modules is made empty. This fixes …
> Cleanup module load

- LICENSE
It looks like the contents of this repository is Apache 2, adding a license file will help users to find the License more easily and GitHub will use it to identify the license of the repository.
> Create Apache 2 LICENSE

- devlib/bin/scripts/shutils.in
On some systems this seems to have no effect, leaving the executed shell in the root cgroup. Before, this function would still execute and the end user would think the desired process was run in the cgroup when infact it had not.
> Validate cgroups_run_into has taken effect

- devlib/target.py
- devlib/utils/ssh.py
Fixes https://github.com/ARM-software/devlib/issues/684
This PR is untested for now.
> Fix __del__ excep

- devlib/collector/dmesg.py
Raise an exception allowing diagnosis when a dmesg line does not match the regex it is supposed to, rather than the cryptic groups() AttributeError on None.
> collector/dmesg: Handle non-matching regex

- devlib/utils/misc.py
Do not assume the value of the property was set before it is deleted.
> utils/misc: Fix AttributeError in tls_property

- devlib/target.py
Some ADB servers may use non-standard port number. Hence, add 'adb_port' property to AndroidTarget class and pass port number down to adb_command().
> target: Properly propagate ADB port information

- tools/android/setup_host.sh
`cpu-checker` was planned to detect availability of KVM acceleration in QEMU by running `kvm-ok` command.
However, the implementation diverged from plan and made `cpu-checker` redundant.
Thus, remove it from apt package list.
> tools/setup_host.sh: Remove unused package cpu-checker

- devlib/module/cgroups.py
- devlib/target.py
- devlib/utils/asyn.py
- setup.py
- tests/test_asyn.py
Considering https://github.com/ARM-software/devlib/issues/682, this PR updates devlib to use `greenlets` in cases where `nest_asyncio` cannot be used (e.g. using `uvloop` event loop).
This alternative path works by using `greenlet` to provide a way for nested coroutines separated from the top-level coroutine by blocking calls to yield their action. 
TODO:
Fixes #682
> Replace nest_asyncio with greenlets

- devlib/collector/ftrace.py
FtraceCollector.reset() executes 'trace-cmd reset ..' command which
clears all kprobes. This breaks tracing existing kprobe events (if any).
Thus, save kprobe events before trace-cmd reset and restore them after
the reset operation.
For the context, I want to trace an ordinary function in kernel (e.g.,
"echo 'p do_sys_open' > /sys/kernel/tracing/kprobe_events"). However,
FtraceCollector.reset() destroys kprobes, too. Preserving existing
kprobes allows me to use FtraceCollector class as is.
Signed-off-by: Metin Kaya <metin.kaya@arm.com>
> ftrace: Preserve kprobe events during trace-cmd reset

- devlib/collector/dmesg.py
Some drivers emit broken multiline dmesg output (with some Windows-style newline ...) . In order to parse the rest of the content, allow not raising on such input.
> collector/dmesg: Allow not raising on dmesg output parsing failure

- devlib/collector/ftrace.py
self.kprobe_events is actually a path to a file, so should be suffixed _file like all the others.
> collector/ftrace: Fix FtraceCollector.kprobe_events attr name

- devlib/collector/ftrace.py
Deal cleanly with kernels that are compiled without kprobe events.
> collector/ftrace: Handle missing kprobe_events file

- devlib/utils/android.py
The current behavior is to issue "adb unroot" if the device needed to be rooted upon connection. This breaks use of nested Targets, which LISA requires as some target interaction needs to happen in a subprocess.
Fix that by restoring the same adb root state that there was when creating the connection, rather than blindly unrooting the device upon disconnection.
> utils/android: Restore adb root state when disconnecting

- devlib/target.py
The logic in Target.disconnect() appears to have been duplicated by error. While _probably_ harmless, this is at least confusing, and since this happens outside of the lock, this may actually be a real problem.
> target: Remove duplicated disconnection logic

- devlib/bin/scripts/devlib-signal-target
- devlib/collector/ftrace.py
- devlib/connection.py
- devlib/host.py
- devlib/module/cgroups2.py
- devlib/target.py
- devlib/utils/android.py
- devlib/utils/ssh.py
Fixes https://github.com/ARM-software/devlib/issues/645
Supersedes https://github.com/ARM-software/devlib/pull/643
TODO:
Closes https://github.com/ARM-software/devlib/pull/643
> Fix BackgroundCommand.send_signal() and add trace-cmd record support

- devlib/utils/asyn.py
- tests/test_asyn.py
Ensure the canceled tasks are awaited, so cancellation actually takes place.
> utils/asyn: Fix cancellation of async tasks in map_concurrently()

- devlib/collector/ftrace.py
Abandon the use of non-toplevel buffer instance (-B parameter), as they are not worth the hassle. A number of frace features do not interact well with them such as:
* bprint event emitted by trace_printk(), that always lands in the top-level buffer no matter what.
* synthetic events that can also only reasonably be emitted in the top-level buffer as of Linux 6.13
> collector/ftrace: Use top-level buffer instance

- devlib/utils/android.py
- doc/connection.rst
Switch to have check_exit_code=True just like any other connection.
The current behavior will not raise any exception if the command returns a non-zero exit code. This leads to failed attempt at parsing the output, which is now an error message rather than the expected data. Worse, the caller may never realize the command failed. This is especially bad as that behavior will only manifest itself when things go wrong, which is not the majority of the time, leading to code that seems to work ok, but does not handle failure properly (like a shell script). Lastly, since this is at odds with all the other connection types, generic code will typically assume check_exit_code=True by default and end up being buggy when used in conjunction of the AdbConnection.
> utils/android: Fix AdbConnection.execute(check_exit_code=False) default
